#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    device_models:
        description:
          - Defines the SD-WAN device type for template application.
        type: list
        default: []
        elements: str
        choices:
        - "None"
        - "vsmart"
        - "vedge-cloud"
        - "vmanage"
        - "vedge-ISR1100-6G"
        - "vedge-ISR1100X-6G"
        - "vedge-ISR1100-4G"
        - "vedge-ISR1100X-4G"
        - "vedge-ISR1100-4GLTE"
        - "vedge-1000"
        - "vedge-2000"
        - "vedge-100"
        - "vedge-100-B"
        - "vedge-100-WM"
        - "vedge-100-M"
        - "vedge-5000"
        - "vedge-IR-1101"
        - "vedge-ESR-6300"
        - "vedge-IR-1821"
        - "vedge-IR-1831"
        - "vedge-IR-1833"
        - "vedge-IR-1835"
        - "vedge-ASR-1001-X"
        - "vedge-ASR-1002-X"
        - "vedge-ASR-1002-HX"
        - "vedge-ASR-1001-HX"
        - "vedge-C8500L-8G4X"
        - "vedge-C8500-12X4QC"
        - "vedge-C8500-12X"
        - "vedge-C8500L-8S4X"
        - "vedge-ASR-1006-X"
        - "vedge-C8500-20X6C"
        - "vedge-CSR-1000v"
        - "vedge-C8000V"
        - "vedge-ISR-4331"
        - "vedge-ISR-4431"
        - "vedge-ISR-4461"
        - "vedge-ISR-4451-X"
        - "vedge-ISR-4321"
        - "vedge-ISR-4351"
        - "vedge-ISR-4221"
        - "vedge-ISR-4221X"
        - "vedge-C1111-8PW"
        - "vedge-C1111-8PLTELAW"
        - "vedge-C1111-8PLTEEAW"
        - "vedge-C1113-8PMLTEEA"
        - "vedge-C1116-4P"
        - "vedge-C1116-4PLTEEA"
        - "vedge-C1117-4P"
        - "vedge-C1117-4PM"
        - "vedge-C1117-4PLTEEA"
        - "vedge-C1111-8PLTELA"
        - "vedge-C1111-8PLTEEA"
        - "vedge-C1121-8PLTEPW"
        - "vedge-C1121-8PLTEP"
        - "vedge-C1121X-8PLTEP"
        - "vedge-C1111-4PLTEEA"
        - "vedge-C1161X-8PLTEP"
        - "vedge-C8300-2N2S-6T"
        - "vedge-C8300-1N1S-6T"
        - "vedge-C8300-1N1S-4T2X"
        - "vedge-C8300-2N2S-4T2X"
        - "vedge-C8200-1N-4T"
        - "vedge-C8200L-1N-4T"
        - "vedge-ISRv"
    """
