#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    aaa:
        description: AAA Feature Template configuration
        type: dict
        suboptions:
            auth_order:
                description:
                - ServerGroups authentication order to user access
                required: false
                default:
                - local
                - radius
                - tacacs
                type: list
                elements: str
                choices:
                - local
                - radius
                - tacacs
            auth_fallback:
                description:
                - Authenticate admin user as per auth-order
                required: false
                default: false
                type: bool
            admin_auth_order:
                description:
                - Fall back if higher-priority authentication fails
                required: false
                default: false
                type: bool
            netconf_disable:
                description:
                - Disable Netconf logs
                required: false
                default: false
                type: bool
            audit_disable:
                description:
                - Disable audit logs
                required: false
                default: false
                type: bool
            radius_server_list:
                description:
                - Designate radius servers for authentication and accounting
                required: false
                default: null
                type: list
                elements: str
            task:
                description:
                - Set the user group's tasks and task privileges.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - The name of the user
                        required: true
                        default: null
                        type: str
                    config_default_action:
                        description:
                        - Define config default action
                        required: true
                        default: null
                        type: str
                        choices:
                        - accept
                        - deny
                    oper_exec_default_action:
                        description:
                        - Define oper-exec default action
                        required: true
                        default: null
                        type: str
                        choices:
                        - accept
                        - deny
                    oper_exec_accept_action:
                        description:
                        - List of oper-exec commands to allow
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            command:
                                description:
                                - Define command
                                required: true
                                default: null
                                type: str
                    oper_exec_deny_action:
                        description:
                        - List of oper-exec commands to deny
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            command:
                                description:
                                - Define command
                                required: true
                                default: null
                                type: str
                    config_accept_action:
                        description:
                        - List of config commands to allow
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            command:
                                description:
                                - Define command
                                required: true
                                default: null
                                type: str
                    config_deny_action:
                        description:
                        - List of config commands to deny
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            command:
                                description:
                                - Define command
                                required: true
                                default: null
                                type: str
                    password:
                        description:
                        - The password for the user
                        required: false
                        default: null
                        type: str
                    secret:
                        description:
                        - The secret for the user
                        required: false
                        default: null
                        type: str
                    privilege:
                        description:
                        - The privilege level for the user
                        required: false
                        default: '15'
                        type: str
                        choices:
                        - '1'
                        - '15'
            accounting:
                description:
                - Enable/disable user accounting
                required: false
                default: false
                type: bool
            usergroup:
                description:
                - Create groupings of users with the same authorization privileges.
                    When used, overrides existing groups(netadmin, basic, operator)
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - Set name of user group
                        required: true
                        default: null
                        type: str
                    task:
                        description:
                        - Set the user group's tasks and task privileges. Skipping
                            tasks sets all as read and write
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            mode:
                                description:
                                - Select the task to set privileges for
                                required: true
                                default: null
                                type: str
                                choices:
                                - system
                                - interface
                                - policy
                                - routing
                                - security
                            permission:
                                description:
                                - Set read or write permission for the task
                                required: false
                                default: pap
                                type: list
                                elements: str
                                choices:
                                - read
                                - write
            user:
                description:
                - List of local user configurations. When used, overrides existing
                    users
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - The name of the user
                        required: true
                        default: null
                        type: str
                    password:
                        description:
                        - The password for the user
                        required: false
                        default: null
                        type: str
                    secret:
                        description:
                        - The secret for the user
                        required: false
                        default: null
                        type: str
                    description:
                        description:
                        - Add a description of the user
                        required: false
                        default: null
                        type: str
                    group:
                        description:
                        - Configure the groups that the user is part of
                        required: false
                        default: null
                        type: list
                        elements: str
                    pubkey_chain:
                        description:
                        - List of public keys for the user
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            usertag:
                                description:
                                - User Tag
                                required: true
                                default: null
                                type: str
                            key_string:
                                description:
                                - Set the RSA key string
                                required: true
                                default: null
                                type: str
                            key_type:
                                description:
                                - Only RSA is supported
                                required: false
                                default: ssh-rsa
                                type: str
            cisco_tac_ro_user:
                description:
                - Cisco Tac Enable Read only
                required: false
                default: true
                type: bool
            cisco_tac_rw_user:
                description:
                - Cisco Tac Enable Read and Write
                required: false
                default: true
                type: bool
            tacacs_timeout:
                description:
                - The timeout period in seconds for the TACACS+ server
                required: false
                default: null
                type: int
            tacacs_authentication:
                description:
                - TACACS authentication type
                required: false
                default: pap
                type: str
                choices:
                - pap
                - ascii
            tacacs_server:
                description:
                - The list of TACACS+ servers
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    address:
                        description:
                        - The IP address or hostname of the TACACS+ server
                        required: true
                        default: null
                        type: str
                    auth_port:
                        description:
                        - The authentication port for the TACACS+ server
                        required: false
                        default: null
                        type: int
                    vpn:
                        description:
                        - Set VPN in which TACACS+ server is located
                        required: false
                        default: null
                        type: str
                    source_interface:
                        description:
                        - Set interface to use to reach TACACS+ server
                        required: false
                        default: null
                        type: str
                    key:
                        description:
                        - Set the password to access the TACACS+ server
                        required: false
                        default: null
                        type: str
                    secret_key:
                        description:
                        - Set the AES encrypted key to access the TACACS+ server
                        required: false
                        default: null
                        type: str
                    priority:
                        description:
                        - TACACS+ server priority <0..7>
                        required: false
                        default: null
                        type: int
            radius_timeout:
                description:
                - The timeout period in seconds for the RADIUS server
                required: false
                default: null
                type: int
            radius_retransmit:
                description:
                - The number of retransmit attempts for the RADIUS server
                required: false
                default: null
                type: int
            radius_server:
                description:
                - The list of RADIUS servers
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    address:
                        description:
                        - The IP address or hostname of the RADIUS server
                        required: true
                        default: null
                        type: str
                    auth_port:
                        description:
                        - The authentication port for the RADIUS server
                        required: false
                        default: null
                        type: int
                    tag:
                        description:
                        - Reference tag/name for the server
                        required: false
                        default: null
                        type: str
                    acct_port:
                        description:
                        - The accounting port for the RADIUS server
                        required: false
                        default: null
                        type: int
                    vpn:
                        description:
                        - Set VPN in which RADIUS server is located
                        required: false
                        default: null
                        type: str
                    source_interface:
                        description:
                        - Set interface to use to reach RADIUS server
                        required: false
                        default: null
                        type: str
                    key:
                        description:
                        - Set the password to access the RADIUS server
                        required: false
                        default: null
                        type: str
                    secret_key:
                        description:
                        - Set the AES encrypted key to access the RADIUS server
                        required: false
                        default: null
                        type: str
                    priority:
                        description:
                        - RADIUS server priority <0..7>
                        required: false
                        default: null
                        type: int
    """
