#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    cisco_banner:
        description: Cisco Banner configuration for login and message of the day (MOTD)
        type: dict
        suboptions:
            login_banner:
                description:
                - The login banner text displayed before authentication
                required: false
                default: null
                type: str
            motd_banner:
                description:
                - The message of the day (MOTD) banner text displayed after successful
                    authentication
                required: false
                default: null
                type: str
    """
