#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    cisco_secure_internet_gateway:
        description: Cisco Secure Internet Gateway feature template configuration
        type: dict
        suboptions:
            vpn_id:
                description:
                - VPN ID associated with the Cisco Secure Internet Gateway service.
                required: false
                default: null
                type: int
            child_org_id:
                description:
                - Child Organization Id
                required: false
                default: ''
                type: str
            interface:
                description:
                - List of interface configurations associated with the service.
                required: true
                default: null
                type: list
                elements: dict
                suboptions:
                    if_name:
                        description:
                        - Name of the interface.
                        required: true
                        default: null
                        type: str
                    auto:
                        description:
                        - Flag to indicate if the interface should be automatically
                            configured.
                        required: true
                        default: null
                        type: bool
                    shutdown:
                        description:
                        - Flag to indicate if the interface is administratively down
                            (shutdown).
                        required: true
                        default: null
                        type: bool
                    description:
                        description:
                        - Description for the interface.
                        required: false
                        default: null
                        type: str
                    unnumbered:
                        description:
                        - Flag to indicate if the interface should be unnumbered.
                        required: false
                        default: null
                        type: bool
                    address:
                        description:
                        - IPv4 address and subnet mask for the interface.
                        required: false
                        default: null
                        type: str
                    tunnel_source:
                        description:
                        - IPv4 address used as the source of the tunnel.
                        required: false
                        default: null
                        type: str
                    tunnel_source_interface:
                        description:
                        - Interface name used as the source of the tunnel.
                        required: false
                        default: null
                        type: str
                    tunnel_route_via:
                        description:
                        - The route via which tunnel traffic should be sent.
                        required: false
                        default: null
                        type: str
                    tunnel_destination:
                        description:
                        - The destination address for the tunnel.
                        required: true
                        default: null
                        type: str
                    application:
                        description:
                        - Application type for the Secure Internet Gateway.
                        required: false
                        default: sig
                        type: str
                        choices:
                        - sig
                    tunnel_set:
                        description:
                        - Tunnel set used for the Secure Internet Gateway.
                        required: false
                        default: secure-internet-gateway-umbrella
                        type: str
                        choices:
                        - secure-internet-gateway-umbrella
                        - secure-internet-gateway-zscaler
                    tunnel_dc_preference:
                        description:
                        - Data center preference for the tunnel.
                        required: false
                        default: primary-dc
                        type: str
                        choices:
                        - primary-dc
                        - secondary-dc
                    tcp_mss_adjust:
                        description:
                        - TCP Maximum Segment Size (MSS) adjust value.
                        required: false
                        default: null
                        type: int
                    mtu:
                        description:
                        - MTU (Maximum Transmission Unit) size for the interface.
                        required: false
                        default: null
                        type: int
                    dpd_interval:
                        description:
                        - Dead Peer Detection (DPD) interval in seconds.
                        required: false
                        default: null
                        type: int
                    dpd_retries:
                        description:
                        - Number of retries for Dead Peer Detection (DPD).
                        required: false
                        default: null
                        type: int
                    ike_version:
                        description:
                        - Internet Key Exchange (IKE) protocol version.
                        required: false
                        default: null
                        type: int
                    pre_shared_secret:
                        description:
                        - Pre-shared secret key for IKE authentication.
                        required: false
                        default: null
                        type: str
                    ike_rekey_interval:
                        description:
                        - Interval for rekeying the IKE security association.
                        required: false
                        default: null
                        type: int
                    ike_ciphersuite:
                        description:
                        - Ciphersuite for IKE security association establishment.
                        required: false
                        default: aes256-cbc-sha1
                        type: str
                        choices:
                        - aes256-cbc-sha1
                        - aes256-cbc-sha2
                        - aes128-cbc-sha1
                        - aes128-cbc-sha2
                    ike_group:
                        description:
                        - Diffie-Hellman group used for IKE key exchange.
                        required: false
                        default: '14'
                        type: str
                        choices:
                        - '2'
                        - '14'
                        - '15'
                        - '16'
                    pre_shared_key_dynamic:
                        description:
                        - Flag indicating if the pre-shared key is dynamic.
                        required: false
                        default: null
                        type: bool
                    ike_local_id:
                        description:
                        - Local identifier for IKE authentication.
                        required: false
                        default: null
                        type: str
                    ike_remote_id:
                        description:
                        - Remote identifier for IKE authentication.
                        required: false
                        default: null
                        type: str
                    ipsec_rekey_interval:
                        description:
                        - Interval for rekeying the IPsec security association.
                        required: false
                        default: null
                        type: int
                    ipsec_replay_window:
                        description:
                        - Replay window size for IPsec security association.
                        required: false
                        default: null
                        type: int
                    ipsec_ciphersuite:
                        description:
                        - Ciphersuite for IPsec security association establishment.
                        required: false
                        default: aes256-gcm
                        type: str
                        choices:
                        - aes256-cbc-sha1
                        - aes256-cbc-sha384
                        - aes256-cbc-sha256
                        - aes256-cbc-sha512
                        - aes256-gcm
                        - null-sha1
                        - null-sha384
                        - null-sha256
                        - null-sha512
                    perfect_forward_secrecy:
                        description:
                        - Perfect Forward Secrecy (PFS) setting for IPsec key exchange.
                        required: false
                        default: none
                        type: str
                        choices:
                        - group-2
                        - group-14
                        - group-15
                        - group-16
                        - none
                    tracker:
                        description:
                        - Flag indicating if interface tracking is enabled.
                        required: false
                        default: null
                        type: bool
                    track_enable:
                        description:
                        - Flag indicating if tracking is enabled for the interface.
                        required: false
                        default: null
                        type: bool
                    tunnel_public_ip:
                        description:
                        - Public IP required to setup GRE tunnel to Zscaler
                        required: false
                        default: null
                        type: str
            service:
                description:
                - List of service configurations for the Cisco Secure Internet Gateway.
                required: true
                default: null
                type: list
                elements: dict
                suboptions:
                    svc_type:
                        description:
                        - Type of service configured.
                        required: false
                        default: sig
                        type: str
                        choices:
                        - sig
                    interface_pair:
                        description:
                        - List of high-availability interface pairs.
                        required: true
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            active_interface:
                                description:
                                - Name of the active interface.
                                required: true
                                default: null
                                type: str
                            active_interface_weight:
                                description:
                                - Weighting factor for the active interface, used
                                    in failover decisions.
                                required: false
                                default: null
                                type: int
                            backup_interface:
                                description:
                                - Name of the backup interface. Can be 'None' if no
                                    backup interface is defined.
                                required: false
                                default: null
                                type: str
                            backup_interface_weight:
                                description:
                                - Weighting factor for the backup interface, used
                                    in failover decisions.
                                required: false
                                default: null
                                type: int
                    auth_required:
                        description:
                        - Flag indicating if authentication is required for the service.
                        required: false
                        default: null
                        type: bool
                    xff_forward_enabled:
                        description:
                        - Flag indicating if X-Forwarded-For HTTP header is enabled.
                        required: false
                        default: null
                        type: bool
                    ofw_enabled:
                        description:
                        - Flag indicating if on-premise firewall is enabled.
                        required: false
                        default: null
                        type: bool
                    ips_control:
                        description:
                        - Flag indicating if Intrusion Prevention System (IPS) control
                            is enabled.
                        required: false
                        default: null
                        type: bool
                    caution_enabled:
                        description:
                        - Flag indicating if caution warnings are enabled.
                        required: false
                        default: null
                        type: bool
                    primary_data_center:
                        description:
                        - Primary data center for the service. 'Auto' for automatic
                            selection.
                        required: false
                        default: Auto
                        type: str
                    secondary_data_center:
                        description:
                        - Secondary data center for the service. 'Auto' for automatic
                            selection.
                        required: false
                        default: Auto
                        type: str
                    ip:
                        description:
                        - Flag indicating if IP filtering or processing is enabled
                            for the service.
                        required: false
                        default: null
                        type: bool
                    idle_time:
                        description:
                        - Idle time before a session is considered inactive.
                        required: false
                        default: null
                        type: int
                    display_time_unit:
                        description:
                        - Unit of time used for displaying time-related settings.
                        required: false
                        default: MINUTE
                        type: str
                        choices:
                        - MINUTE
                        - HOUR
                        - DAY
                    ip_enforced_for_known_browsers:
                        description:
                        - Flag indicating if IP is enforced for known browsers.
                        required: false
                        default: null
                        type: bool
                    refresh_time:
                        description:
                        - Time after which the service information is refreshed.
                        required: false
                        default: null
                        type: int
                    refresh_time_unit:
                        description:
                        - Unit of time used for the refresh time setting.
                        required: false
                        default: MINUTE
                        type: str
                        choices:
                        - MINUTE
                        - HOUR
                        - DAY
                    enabled:
                        description:
                        - Flag indicating if the service is enabled.
                        required: false
                        default: null
                        type: bool
                    block_internet_until_accepted:
                        description:
                        - Flag indicating if Internet access is blocked until the
                            service is accepted.
                        required: false
                        default: null
                        type: bool
                    force_ssl_inspection:
                        description:
                        - Flag indicating if SSL inspection is forced.
                        required: false
                        default: null
                        type: bool
                    timeout:
                        description:
                        - Timeout value for the service, after which the session is
                            considered inactive.
                        required: false
                        default: null
                        type: int
                    location_name:
                        description:
                        - Secondary data center for the service. 'Auto' for automatic
                            selection.
                        required: false
                        default: Auto
                        type: str
                    data_center_primary:
                        description:
                        - Zscaler location name (optional)
                        required: false
                        default: Auto
                        type: str
                    data_center_secondary:
                        description:
                        - Secondary data center for the service. 'Auto' for automatic
                            selection or a specific identifier for a manual selection.
                        required: false
                        default: Auto
                        type: str
            tracker_src_ip:
                description:
                - Source IP address used by the tracker for sending health check packets.
                required: false
                default: null
                type: str
            tracker:
                description:
                - List of trackers for monitoring the health of the Cisco Secure Internet
                    Gateway service.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - Name of the tracker.
                        required: true
                        default: null
                        type: str
                    endpoint_api_url:
                        description:
                        - URL of the endpoint API used by the tracker for health checks.
                        required: true
                        default: null
                        type: str
                    threshold:
                        description:
                        - Threshold value for the tracker to trigger an alert or action.
                        required: false
                        default: null
                        type: int
                    interval:
                        description:
                        - Interval at which the tracker performs health checks.
                        required: false
                        default: null
                        type: int
                    multiplier:
                        description:
                        - Multiplier value used by the tracker to escalate repeated
                            failures.
                        required: false
                        default: null
                        type: int
                    tracker_type:
                        description:
                        - Type of tracker used for monitoring.
                        required: true
                        default: null
                        type: str
                        choices:
                        - SIG
    """
