#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    cisco_vpn_interface:
        description: Cisco VPN Interface Feature Template configuration
        type: dict
        suboptions:
            if_name:
                description:
                - The name of the interface.
                required: false
                default: null
                type: str
            interface_description:
                description:
                - A description for the interface.
                required: false
                default: null
                type: str
            poe:
                description:
                - Power over Ethernet setting for the interface. True if enabled,
                    False otherwise.
                required: false
                default: null
                type: bool
            ipv4_address:
                description:
                - The primary IPv4 address assigned to the interface.
                required: false
                default: null
                type: str
            secondary_ipv4_address:
                description:
                - A list of secondary IPv4 addresses assigned to the interface.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    address:
                        description:
                        - IPv4 address with CIDR notation for the secondary interface.
                        required: false
                        default: null
                        type: str
            dhcp_ipv4_client:
                description:
                - Whether DHCP client is enabled on the interface for IPv4 addressing.
                    True if enabled, False otherwise.
                required: false
                default: null
                type: bool
            dhcp_distance:
                description:
                - Administrative distance for DHCP routes on the interface.
                required: false
                default: null
                type: int
            ipv6_address:
                description:
                - The primary IPv6 address assigned to the interface.
                required: false
                default: null
                type: str
            dhcp_ipv6_client:
                description:
                - Whether DHCP client is enabled on the interface for IPv6 addressing.
                    True if enabled, False otherwise.
                required: false
                default: null
                type: bool
            secondary_ipv6_address:
                description:
                - A list of secondary IPv6 addresses assigned to the interface.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    address:
                        description:
                        - IPv6 address with CIDR notation for the secondary interface.
                        required: false
                        default: null
                        type: str
            access_list_ipv4:
                description:
                - A list of IPv4 access control lists (ACLs) applied to the interface.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    direction:
                        description:
                        - Direction of the traffic flow for applying the ACL ('in'
                            or 'out').
                        required: true
                        default: null
                        type: str
                        choices:
                        - in
                        - out
                    acl_name:
                        description:
                        - Name of the access control list.
                        required: true
                        default: null
                        type: str
            dhcp_helper:
                description:
                - A list of DHCP helper addresses configured on the interface.
                required: false
                default: null
                type: list
                elements: str
            dhcp_helper_v6:
                description:
                - A list of DHCPv6 helper configurations applied to the interface.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    address:
                        description:
                        - IPv6 address of the DHCP server or relay.
                        required: true
                        default: null
                        type: str
                    vpn:
                        description:
                        - Optional VPN ID where the DHCP helper is configured.
                        required: false
                        default: null
                        type: int
            tracker:
                description:
                - A list of tracker identifiers associated with the interface.
                required: false
                default: null
                type: list
                elements: str
            auto_bandwidth_detect:
                description:
                - Whether automatic bandwidth detection is enabled on the interface.
                    True if enabled, False otherwise.
                required: false
                default: null
                type: bool
            iperf_server:
                description:
                - The IP address of the iPerf server used for performance testing
                    from this interface.
                required: false
                default: null
                type: str
            nat:
                description:
                - Indicates whether Network Address Translation (NAT) is enabled on
                    the interface.
                required: false
                default: null
                type: bool
            nat_choice:
                description:
                - The type of NAT configured on the interface, if applicable.
                required: false
                default: null
                type: str
                choices:
                - Interface
                - Pool
                - Loopback
            udp_timeout:
                description:
                - The timeout value in seconds for UDP connections through the NAT
                    on this interface.
                required: false
                default: null
                type: int
            tcp_timeout:
                description:
                - The timeout value in seconds for TCP connections through the NAT
                    on this interface.
                required: false
                default: null
                type: int
            nat_range_start:
                description:
                - The starting IP address in the range used for NAT on this interface.
                required: false
                default: null
                type: str
            nat_range_end:
                description:
                - The ending IP address in the range used for NAT on this interface.
                required: false
                default: null
                type: str
            overload:
                description:
                - Indicates if NAT overload (PAT - Port Address Translation) is enabled.
                required: false
                default: null
                type: bool
            loopback_interface:
                description:
                - The associated loopback interface, if any, for the VPN interface.
                required: false
                default: null
                type: str
            prefix_length:
                description:
                - The prefix length for the interface's IP address, indicating the
                    size of the subnet.
                required: false
                default: null
                type: int
            enable:
                description:
                - Indicates whether the interface is enabled or disabled.
                required: false
                default: null
                type: bool
            nat64:
                description:
                - Indicates whether NAT64 is enabled on the interface, allowing IPv6
                    addresses to communicate with IPv4 services.
                required: false
                default: null
                type: bool
            nat66:
                description:
                - Indicates whether NAT66 is enabled on the interface, translating
                    IPv6 addresses into IPv6 addresses.
                required: false
                default: null
                type: bool
            static_nat66:
                description:
                - List of static NAT66 entries for translating IPv6 addresses into
                    other IPv6 addresses.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    source_prefix:
                        description:
                        - IPv6 network prefix that is to be translated.
                        required: true
                        default: null
                        type: str
                    translated_source_prefix:
                        description:
                        - IPv6 network prefix to which the source prefix is translated.
                        required: true
                        default: null
                        type: str
                    source_vpn_id:
                        description:
                        - VPN ID associated with the source network prefix.
                        required: false
                        default: null
                        type: int
            static:
                description:
                - List of static NAT entries for configuring one-to-one address mappings.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    source_ip:
                        description:
                        - IPv4 address of the source IP for static NAT.
                        required: true
                        default: null
                        type: str
                    translate_ip:
                        description:
                        - IPv4 address used for translation in static NAT.
                        required: true
                        default: null
                        type: str
                    static_nat_direction:
                        description:
                        - Direction of static NAT mapping ('inside' or 'outside').
                        required: false
                        default: inside
                        type: str
                        choices:
                        - inside
                        - outside
                    source_vpn:
                        description:
                        - VPN ID associated with the source IP for static NAT.
                        required: false
                        default: null
                        type: int
            static_port_forward:
                description:
                - List of static port forwarding entries for the interface.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    source_ip:
                        description:
                        - IPv4 address of the source IP for port forwarding.
                        required: true
                        default: null
                        type: str
                    translate_ip:
                        description:
                        - IPv4 address used for translation in port forwarding.
                        required: true
                        default: null
                        type: str
                    static_nat_direction:
                        description:
                        - Direction of port forwarding mapping ('inside' or 'outside').
                        required: false
                        default: inside
                        type: str
                        choices:
                        - inside
                        - outside
                    source_port:
                        description:
                        - Source port number for port forwarding.
                        required: false
                        default: null
                        type: int
                    translate_port:
                        description:
                        - Translated port number for port forwarding.
                        required: false
                        default: null
                        type: int
                    proto:
                        description:
                        - Protocol used for port forwarding (TCP/UDP).
                        required: true
                        default: null
                        type: str
                        choices:
                        - tcp
                        - udp
                    source_vpn:
                        description:
                        - VPN ID associated with the source IP for port forwarding.
                        required: false
                        default: null
                        type: int
            enable_core_region:
                description:
                - Indicates if the interface is part of the core network region for
                    centralized services.
                required: false
                default: null
                type: bool
            core_region:
                description:
                - Configuration details for the core region.
                required: false
                default: null
                type: str
                choices:
                - core
                - core-shared
            secondary_region:
                description:
                - Configuration details for a secondary region.
                required: false
                default: null
                type: str
                choices:
                - 'off'
                - secondary-only
                - secondary-shared
            tloc_encapsulation:
                description:
                - Transport Location (TLOC) encapsulation settings.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    encap:
                        description:
                        - Type of encapsulation used for the VPN tunnel (GRE/IPsec).
                        required: true
                        default: null
                        type: str
                        choices:
                        - gre
                        - ipsec
                    preference:
                        description:
                        - Preference value for the encapsulation type (lower values
                            have higher priority).
                        required: false
                        default: null
                        type: int
                    weight:
                        description:
                        - Weight for the encapsulation type used in load balancing
                            decisions.
                        required: false
                        default: null
                        type: int
            border:
                description:
                - Defines if the interface is at the border of a network segment.
                required: false
                default: null
                type: bool
            per_tunnel_qos:
                description:
                - Enable or disable per-tunnel Quality of Service (QoS).
                required: false
                default: null
                type: bool
            per_tunnel_qos_aggregator:
                description:
                - Enable or disable per-tunnel QoS aggregator.
                required: false
                default: null
                type: bool
            mode:
                description:
                - Defines the operating mode for the interface.
                required: false
                default: null
                type: str
                choices:
                - hub
                - spoke
            tunnels_bandwidth:
                description:
                - Specifies the total bandwidth available across all tunnels.
                required: false
                default: null
                type: int
            group:
                description:
                - Identifies the group or groups the interface belongs to.
                required: false
                default: null
                type: list
                elements: int
            value:
                description:
                - The value field often corresponds to a specific attribute or setting,
                    such as color in this context.
                required: false
                default: null
                type: str
                choices:
                - default
                - mpls
                - metro-ethernet
                - biz-internet
                - public-internet
                - lte
                - 3g
                - red
                - green
                - blue
                - gold
                - silver
                - bronze
                - custom1
                - custom2
                - custom3
                - private1
                - private2
                - private3
                - private4
                - private5
                - private6
            max_control_connections:
                description:
                - Maximum number of control connections that can be established on
                    the interface.
                required: false
                default: null
                type: int
            control_connections:
                description:
                - Enables or disables control connections on the interface.
                required: false
                default: null
                type: bool
            vbond_as_stun_server:
                description:
                - Configures the vBond orchestrator to act as a STUN server for the
                    interface.
                required: false
                default: null
                type: bool
            exclude_controller_group_list:
                description:
                - List of controller groups to exclude from connections.
                required: false
                default: null
                type: list
                elements: int
            vmanage_connection_preference:
                description:
                - Preference value for establishing vManage connections.
                required: false
                default: null
                type: int
            port_hop:
                description:
                - Enables or disables port hopping for the interface to evade port
                    blocking.
                required: false
                default: null
                type: bool
            restrict:
                description:
                - Indicates whether the interface color is restricted for use.
                required: false
                default: null
                type: bool
            dst_ip:
                description:
                - Destination IP address for GRE (Generic Routing Encapsulation) tunnel
                    extension.
                required: false
                default: null
                type: str
            carrier:
                description:
                - Specifies the carrier information for the tunnel interface.
                required: false
                default: null
                type: str
                choices:
                - default
                - carrier1
                - carrier2
                - carrier3
                - carrier4
                - carrier5
                - carrier6
                - carrier7
                - carrier8
            nat_refresh_interval:
                description:
                - Interval in seconds to refresh NAT (Network Address Translation)
                    mappings.
                required: false
                default: null
                type: int
            hello_interval:
                description:
                - Time interval in seconds between successive hello packets sent over
                    the tunnel interface.
                required: false
                default: null
                type: int
            hello_tolerance:
                description:
                - Time in seconds to wait before declaring a neighbor down due to
                    missing hello packets.
                required: false
                default: null
                type: int
            bind:
                description:
                - Interface or IP address to which the tunnel interface is bound.
                required: false
                default: null
                type: str
            last_resort_circuit:
                description:
                - Marks the interface as a last resort circuit for traffic to fall
                    back to.
                required: false
                default: null
                type: bool
            low_bandwidth_link:
                description:
                - Indicates if the link is considered a low bandwidth link.
                required: false
                default: null
                type: bool
            tunnel_tcp_mss_adjust:
                description:
                - Adjusts the Maximum Segment Size (MSS) value for TCP connections
                    over the tunnel.
                required: false
                default: null
                type: int
            clear_dont_fragment:
                description:
                - Enables or disables the clearing of the 'Don't Fragment' (DF) bit
                    in the IP header.
                required: false
                default: null
                type: bool
            propagate_sgt:
                description:
                - Enables or disables the propagation of Security Group Tags (SGTs)
                    across the tunnel interface.
                required: false
                default: null
                type: bool
            network_broadcast:
                description:
                - Allows or disallows network broadcast traffic through the tunnel
                    interface.
                required: false
                default: null
                type: bool
            all:
                description:
                - Permits or denies all services through the tunnel interface.
                required: false
                default: null
                type: bool
            bgp:
                description:
                - Allows or disallows Border Gateway Protocol (BGP) traffic through
                    the tunnel interface.
                required: false
                default: null
                type: bool
            dhcp:
                description:
                - Enables or disables Dynamic Host Configuration Protocol (DHCP) on
                    the tunnel interface.
                required: false
                default: null
                type: bool
            dns:
                description:
                - Allows or disallows Domain Name System (DNS) queries through the
                    tunnel interface.
                required: false
                default: null
                type: bool
            icmp:
                description:
                - Enables or disables Internet Control Message Protocol (ICMP) for
                    ping and traceroute through the tunnel interface.
                required: false
                default: null
                type: bool
            sshd:
                description:
                - Allows or disallows Secure Shell (SSH) daemon access through the
                    tunnel interface.
                required: false
                default: null
                type: bool
            netconf:
                description:
                - Enables or disables NETCONF protocol support on the tunnel interface.
                required: false
                default: null
                type: bool
            ntp:
                description:
                - Allows or disallows Network Time Protocol (NTP) synchronization
                    through the tunnel interface.
                required: false
                default: null
                type: bool
            ospf:
                description:
                - Permits or denies Open Shortest Path First (OSPF) routing protocol
                    traffic through the tunnel interface.
                required: false
                default: null
                type: bool
            stun:
                description:
                - Enables or disables Session Traversal Utilities for NAT (STUN) on
                    the tunnel interface.
                required: false
                default: null
                type: bool
            snmp:
                description:
                - Allows or disallows Simple Network Management Protocol (SNMP) through
                    the tunnel interface.
                required: false
                default: null
                type: bool
            https:
                description:
                - Permits or denies HTTPS traffic through the tunnel interface.
                required: false
                default: null
                type: bool
            media_type:
                description:
                - Specifies the media type used by the interface, such as copper or
                    fiber.
                required: false
                default: null
                type: str
                choices:
                - auto-select
                - rj45
                - sfp
            intrf_mtu:
                description:
                - Sets the Maximum Transmission Unit (MTU) size for the interface.
                required: false
                default: null
                type: int
            mtu:
                description:
                - Specifies the MTU size for the tunnel or logical interface.
                required: false
                default: null
                type: int
            tcp_mss_adjust:
                description:
                - Adjusts the TCP Maximum Segment Size (MSS) value for connections
                    over the interface.
                required: false
                default: null
                type: int
            tloc_extension:
                description:
                - Defines the Transport Location (TLOC) extension for the interface.
                required: false
                default: null
                type: str
            load_interval:
                description:
                - Sets the time interval in seconds for calculating interface load
                    statistics.
                required: false
                default: null
                type: int
            src_ip:
                description:
                - Source IP address for GRE tunnel extension.
                required: false
                default: null
                type: str
            xconnect:
                description:
                - Cross-connect identifier for the GRE tunnel extension.
                required: false
                default: null
                type: str
            mac_address:
                description:
                - Specifies the MAC address for the interface.
                required: false
                default: null
                type: str
            speed:
                description:
                - Defines the speed of the interface, such as 10Mbps, 100Mbps, or
                    1Gbps.
                required: false
                default: null
                type: str
                choices:
                - '10'
                - '100'
                - '1000'
                - '2500'
                - '10000'
            duplex:
                description:
                - Sets the duplex mode for the interface, such as full or half duplex.
                required: false
                default: null
                type: str
                choices:
                - full
                - half
                - auto
            shutdown:
                description:
                - Enables or disables (shuts down) the interface.
                required: false
                default: false
                type: bool
            arp_timeout:
                description:
                - Time in seconds before an ARP cache entry is timed out.
                required: false
                default: null
                type: int
            autonegotiate:
                description:
                - Enables or disables autonegotiation of speed and duplex settings
                    on the interface.
                required: false
                default: null
                type: bool
            ip_directed_broadcast:
                description:
                - Allows or disallows IP directed broadcasts on the interface.
                required: false
                default: null
                type: bool
            icmp_redirect_disable:
                description:
                - Enables or disables ICMP redirect messages on the interface.
                required: false
                default: null
                type: bool
            qos_adaptive:
                description:
                - Activates or deactivates adaptive QoS on the interface.
                required: false
                default: null
                type: bool
            period:
                description:
                - Time period in seconds for measuring and adapting QoS settings.
                required: false
                default: null
                type: int
            bandwidth_down:
                description:
                - Specifies the downstream bandwidth in Kbps for adaptive QoS calculations.
                required: false
                default: null
                type: int
            dmin:
                description:
                - Specifies the minimum downstream bandwidth in Kbps for adaptive
                    QoS.
                required: false
                default: null
                type: int
            dmax:
                description:
                - Specifies the maximum downstream bandwidth in Kbps for adaptive
                    QoS.
                required: false
                default: null
                type: int
            bandwidth_up:
                description:
                - Specifies the upstream bandwidth in Kbps for adaptive QoS calculations.
                required: false
                default: null
                type: int
            umin:
                description:
                - Specifies the minimum upstream bandwidth in Kbps for adaptive QoS.
                required: false
                default: null
                type: int
            umax:
                description:
                - Specifies the maximum upstream bandwidth in Kbps for adaptive QoS.
                required: false
                default: null
                type: int
            shaping_rate:
                description:
                - Defines the traffic shaping rate for the interface.
                required: false
                default: null
                type: int
            qos_map:
                description:
                - Associates a QoS map with the interface for traffic classification
                    and prioritization.
                required: false
                default: null
                type: str
            qos_map_vpn:
                description:
                - Associates a QoS map with a VPN for traffic classification and prioritization
                    within the VPN.
                required: false
                default: null
                type: str
            service_provider:
                description:
                - Identifies the service provider associated with the interface.
                required: false
                default: null
                type: str
            bandwidth_upstream:
                description:
                - Specifies the upstream bandwidth in Kbps available on the interface.
                required: false
                default: null
                type: int
            bandwidth_downstream:
                description:
                - Specifies the downstream bandwidth in Kbps available on the interface.
                required: false
                default: null
                type: int
            block_non_source_ip:
                description:
                - Enables or disables blocking of traffic with non-matching source
                    IP addresses.
                required: false
                default: null
                type: bool
            rule_name:
                description:
                - Specifies the name of the rewrite rule applied to the interface.
                required: false
                default: null
                type: str
            access_list_ipv6:
                description:
                - Defines a list of access control entries for IPv6 traffic filtering.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    direction:
                        description:
                        - Direction of the traffic flow for applying the ACL ('in'
                            or 'out').
                        required: true
                        default: null
                        type: str
                        choices:
                        - in
                        - out
                    acl_name:
                        description:
                        - Name of the access control list.
                        required: true
                        default: null
                        type: str
            ip:
                description:
                - A list of IP configurations for Address Resolution Protocol (ARP)
                    settings.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    addr:
                        description:
                        - IPv4 address for the interface.
                        required: true
                        default: null
                        type: str
                    mac:
                        description:
                        - MAC address associated with the IPv4 address.
                        required: true
                        default: null
                        type: str
            vrrp:
                description:
                - A list of Virtual Router Redundancy Protocol (VRRP) configurations
                    for IPv4.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    grp_id:
                        description:
                        - VRRP group ID.
                        required: true
                        default: null
                        type: int
                    priority:
                        description:
                        - Priority value for the VRRP group (higher values take precedence).
                        required: false
                        default: null
                        type: int
                    timer:
                        description:
                        - VRRP advertisement interval timer in milliseconds.
                        required: false
                        default: null
                        type: int
                    track_omp:
                        description:
                        - Flag to track Overlay Management Protocol (OMP) session
                            state.
                        required: false
                        default: null
                        type: bool
                    track_prefix_list:
                        description:
                        - Name of the prefix-list used for tracking specific routes.
                        required: false
                        default: null
                        type: str
                    address:
                        description:
                        - Virtual IP address used by the VRRP group.
                        required: false
                        default: null
                        type: str
                    ipv4_secondary:
                        description:
                        - List of secondary IPv4 addresses for the VRRP group.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            address:
                                description:
                                - IPv4 address for the secondary interface.
                                required: true
                                default: null
                                type: str
                    tloc_change_pref:
                        description:
                        - Flag to change preference based on TLOC status.
                        required: false
                        default: null
                        type: bool
                    value:
                        description:
                        - VRRP value to determine the primary node for the VRRP group.
                        required: true
                        default: null
                        type: int
                    tracking_object:
                        description:
                        - List of tracking objects associated with the VRRP configuration.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            name:
                                description:
                                - Unique identifier for the tracking object.
                                required: true
                                default: null
                                type: int
                            track_action:
                                description:
                                - Action to take when the tracked object state changes
                                    (e.g., decrement priority or shutdown).
                                required: false
                                default: Decrement
                                type: str
                                choices:
                                - Decrement
                                - Shutdown
                            decrement:
                                description:
                                - Value by which to decrement the VRRP priority when
                                    the tracked object is down.
                                required: true
                                default: null
                                type: int
            ipv6_vrrp:
                description:
                - A list of Virtual Router Redundancy Protocol (VRRP) configurations
                    for IPv6.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    grp_id:
                        description:
                        - IPv6 VRRP group ID.
                        required: true
                        default: null
                        type: int
                    priority:
                        description:
                        - Priority value for the IPv6 VRRP group (higher values take
                            precedence).
                        required: false
                        default: null
                        type: int
                    timer:
                        description:
                        - IPv6 VRRP advertisement interval timer in milliseconds.
                        required: false
                        default: null
                        type: int
                    track_omp:
                        description:
                        - Flag to track Overlay Management Protocol (OMP) session
                            state for IPv6.
                        required: false
                        default: null
                        type: bool
                    track_prefix_list:
                        description:
                        - Name of the IPv6 prefix-list used for tracking specific
                            routes.
                        required: false
                        default: null
                        type: str
                    ipv6:
                        description:
                        - List of IPv6 configurations associated with the VRRP group.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            ipv6_link_local:
                                description:
                                - IPv6 link-local address for the interface.
                                required: true
                                default: null
                                type: str
                            prefix:
                                description:
                                - Optional IPv6 prefix for the interface, with CIDR
                                    notation.
                                required: false
                                default: null
                                type: str
            enable_sgt_propagation:
                description:
                - Enables or disables Security Group Tag (SGT) propagation.
                required: false
                default: null
                type: bool
            security_group_tag:
                description:
                - Specifies a static Security Group Tag (SGT) for the interface.
                required: false
                default: null
                type: int
            trusted:
                description:
                - Marks the interface as trusted or untrusted for TrustSec.
                required: false
                default: null
                type: bool
            enable_sgt_authorization_and_forwarding:
                description:
                - Enables or disables Security Group Tag (SGT) authorization and forwarding.
                required: false
                default: null
                type: bool
            enable_sgt_enforcement:
                description:
                - Activates or deactivates Security Group Tag (SGT) enforcement.
                required: false
                default: null
                type: bool
            enforcement_sgt:
                description:
                - Specifies the Security Group Tag (SGT) to be enforced on the interface.
                required: false
                default: null
                type: int
    """
