#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    cisco_vpn:
        description: Cisco VPN Feature Template configuration.
        type: dict
        suboptions:
            vpn_id:
                description:
                - The unique identifier for the VPN instance (VRF).
                required: false
                default: null
                type: int
            vpn_name:
                description:
                - The name of the VPN instance.
                required: false
                default: null
                type: str
            tenant_vpn_id:
                description:
                - The tenant-specific identifier for the VPN instance, used in multi-tenant
                    environments.
                required: false
                default: null
                type: int
            org_name:
                description:
                - The name of the organization to which the VPN instance belongs.
                required: false
                default: null
                type: str
            omp_admin_distance_ipv4:
                description:
                - The administrative distance for IPv4 routes received over the Overlay
                    Management Protocol (OMP).
                required: false
                default: null
                type: int
            omp_admin_distance_ipv6:
                description:
                - The administrative distance for IPv6 routes received over OMP.
                required: false
                default: null
                type: int
            dns:
                description:
                - A list of DNS configurations for the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    dns_addr:
                        description:
                        - The IP address of the DNS server.
                        required: false
                        default: null
                        type: str
                    role:
                        description:
                        - The role of the DNS server, either 'PRIMARY' or 'SECONDARY'.
                        required: false
                        default: primary
                        type: str
                        choices:
                        - primary
                        - secondary
            dns_ipv6:
                description:
                - A list of DNS configurations for IPv6 within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    dns_addr:
                        description:
                        - The IPv6 address of the DNS server.
                        required: false
                        default: null
                        type: str
                    role:
                        description:
                        - The role of the DNS server for IPv6, optionally either 'PRIMARY'
                            or 'SECONDARY'.
                        required: false
                        default: primary
                        type: str
                        choices:
                        - primary
                        - secondary
            layer4:
                description:
                - A flag indicating whether Layer 4 information is included in the
                    ECMP hash key.
                required: false
                default: null
                type: bool
            host:
                description:
                - A list of host configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    hostname:
                        description:
                        - The hostname of the device.
                        required: true
                        default: null
                        type: str
                    ip:
                        description:
                        - A list of IP addresses associated with the hostname.
                        required: true
                        default: null
                        type: list
                        elements: str
            service:
                description:
                - A list of service configurations associated with the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    svc_type:
                        description:
                        - The type of service to be configured.
                        required: true
                        default: null
                        type: str
                        choices:
                        - FW
                        - IDS
                        - IDP
                        - netsvc1
                        - netsvc2
                        - netsvc3
                        - netsvc4
                        - TE
                        - appqoe
                    address:
                        description:
                        - A list of IP addresses for the service.
                        required: false
                        default: null
                        type: list
                        elements: str
                    interface:
                        description:
                        - The interface associated with the service.
                        required: false
                        default: null
                        type: str
                    track_enable:
                        description:
                        - Indicates whether tracking is enabled for the service.
                        required: false
                        default: null
                        type: bool
            service_route:
                description:
                - A list of service route configurations for directing traffic to
                    services within the VPN.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    prefix:
                        description:
                        - The network prefix for the service route.
                        required: true
                        default: null
                        type: str
                    vpn:
                        description:
                        - The VPN identifier where the service route is to be applied.
                        required: true
                        default: null
                        type: int
                    service:
                        description:
                        - The service associated with the route.
                        required: false
                        default: sig
                        type: str
                        choices:
                        - sig
            route_v4:
                description:
                - A list of IPv4 route configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    prefix:
                        description:
                        - The IPv4 network prefix for the static route.
                        required: false
                        default: null
                        type: str
                    next_hop:
                        description:
                        - A list of IPv4 next hops for the route.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            address:
                                description:
                                - The IP address of the next hop for the route.
                                required: false
                                default: null
                                type: str
                            distance:
                                description:
                                - The administrative distance of the next hop.
                                required: false
                                default: null
                                type: int
                    next_hop_with_track:
                        description:
                        - A list of IPv4 next hops with tracking for the route.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            address:
                                description:
                                - The IP address of the next hop for the route that
                                    requires tracking.
                                required: false
                                default: null
                                type: str
                            distance:
                                description:
                                - The administrative distance of the next hop that
                                    requires tracking.
                                required: false
                                default: null
                                type: int
                            tracker:
                                description:
                                - The tracker associated with this next hop.
                                required: true
                                default: null
                                type: str
                    route_interface:
                        description:
                        - The interface configuration for the IPv4 static route.
                        required: false
                        default: null
                        type: dict
                        elements: dict
                        suboptions:
                            interface_name:
                                description:
                                - The name of the interface used for routing.
                                required: true
                                default: null
                                type: str
                            interface_next_hop:
                                description:
                                - A list of next hops associated with the interface
                                    for routing purposes.
                                required: false
                                default: null
                                type: list
                                elements: dict
                                suboptions:
                                    address:
                                        description:
                                        - The IP address of the next hop for the route.
                                        required: false
                                        default: null
                                        type: str
                                    distance:
                                        description:
                                        - The administrative distance of the next
                                            hop.
                                        required: false
                                        default: null
                                        type: int
                    null0:
                        description:
                        - A flag indicating whether to route traffic to null0 for
                            this static route.
                        required: false
                        default: null
                        type: bool
                    distance:
                        description:
                        - The administrative distance for the static route.
                        required: false
                        default: null
                        type: int
                    vpn:
                        description:
                        - The VPN instance identifier associated with the static route.
                        required: false
                        default: null
                        type: int
                    dhcp:
                        description:
                        - A flag indicating whether DHCP is used for this static route.
                        required: false
                        default: null
                        type: bool
            route_v6:
                description:
                - A list of IPv6 route configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    prefix:
                        description:
                        - The IPv6 network prefix for the static route.
                        required: true
                        default: null
                        type: str
                    next_hop:
                        description:
                        - A list of IPv6 next hops for the route.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            address:
                                description:
                                - The IPv6 address of the next hop for the route.
                                required: true
                                default: null
                                type: str
                            distance:
                                description:
                                - The administrative distance of the IPv6 next hop.
                                required: false
                                default: null
                                type: int
                    null0:
                        description:
                        - A flag indicating whether to route IPv6 traffic to null0
                            for this static route.
                        required: false
                        default: null
                        type: bool
                    vpn:
                        description:
                        - The VPN instance identifier associated with the IPv6 static
                            route.
                        required: false
                        default: null
                        type: int
                    nat:
                        description:
                        - The type of NAT to apply for the IPv6 static route, if applicable.
                        required: false
                        default: null
                        type: str
                        choices:
                        - NAT64
                        - NAT66
            gre_route:
                description:
                - A list of GRE tunnel route configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    prefix:
                        description:
                        - The network prefix for the GRE (Generic Routing Encapsulation)
                            route.
                        required: true
                        default: null
                        type: str
                    vpn:
                        description:
                        - The VPN identifier where the GRE route is to be applied.
                        required: true
                        default: null
                        type: int
                    interface:
                        description:
                        - A list of interfaces associated with the GRE route.
                        required: false
                        default: null
                        type: list
                        elements: str
            ipsec_route:
                description:
                - A list of IPSec route configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    prefix:
                        description:
                        - The network prefix for the IPSec (Internet Protocol Security)
                            route.
                        required: true
                        default: null
                        type: str
                    vpn:
                        description:
                        - The VPN identifier where the IPSec route is to be applied.
                        required: true
                        default: null
                        type: int
                    interface:
                        description:
                        - A list of interfaces associated with the IPSec route.
                        required: false
                        default: null
                        type: list
                        elements: str
            advertise:
                description:
                - A list of configurations for advertising routes via OMP within the
                    VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    protocol:
                        description:
                        - The protocol used for route advertisement.
                        required: true
                        default: null
                        type: str
                        choices:
                        - bgp
                        - ospf
                        - ospfv3
                        - connected
                        - static
                        - network
                        - aggregate
                        - eigrp
                        - lisp
                        - isis
                    route_policy:
                        description:
                        - The route policy associated with advertisement.
                        required: false
                        default: null
                        type: str
                    protocol_sub_type:
                        description:
                        - A list of subtypes for the advertisement protocol.
                        required: false
                        default: null
                        type: list
                        elements: str
                        choices:
                        - external
                    prefix_list:
                        description:
                        - A list of prefix lists associated with the advertisement
                            settings.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            prefix_entry:
                                description:
                                - The network prefix entry for the prefix list.
                                required: true
                                default: null
                                type: str
                            aggregate_only:
                                description:
                                - A flag indicating if only aggregate routes should
                                    be considered.
                                required: false
                                default: null
                                type: bool
                            region:
                                description:
                                - The network region where the prefix list is applied.
                                required: false
                                default: null
                                type: str
                                choices:
                                - core
                                - access
            ipv6_advertise:
                description:
                - A list of configurations for advertising IPv6 routes via OMP within
                    the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    protocol:
                        description:
                        - The IPv6 protocol used for route advertisement.
                        required: true
                        default: null
                        type: str
                        choices:
                        - bgp
                        - ospf
                        - connected
                        - static
                        - network
                        - aggregate
                    route_policy:
                        description:
                        - The IPv6 route policy associated with advertisement.
                        required: false
                        default: null
                        type: str
                    protocol_sub_type:
                        description:
                        - A list of subtypes for the IPv6 advertisement protocol.
                        required: false
                        default: null
                        type: list
                        elements: str
                        choices:
                        - external
                    prefix_list:
                        description:
                        - A list of IPv6 prefix lists associated with the advertisement
                            settings.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            prefix_entry:
                                description:
                                - The network prefix entry for the prefix list.
                                required: true
                                default: null
                                type: str
                            aggregate_only:
                                description:
                                - A flag indicating if only aggregate routes should
                                    be considered.
                                required: false
                                default: null
                                type: bool
                            region:
                                description:
                                - The network region where the prefix list is applied.
                                required: false
                                default: null
                                type: str
                                choices:
                                - core
                                - access
            pool:
                description:
                - A list of NAT64 pool configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - The name of the IP address pool.
                        required: true
                        default: null
                        type: str
                    start_address:
                        description:
                        - The starting IP address of the pool.
                        required: true
                        default: null
                        type: str
                    end_address:
                        description:
                        - The ending IP address of the pool.
                        required: true
                        default: null
                        type: str
                    overload:
                        description:
                        - A flag indicating whether address overload is allowed.
                        required: false
                        default: null
                        type: bool
                    leak_from_global:
                        description:
                        - A flag indicating whether leaking from the global table
                            is enabled.
                        required: true
                        default: null
                        type: bool
                    leak_from_global_protocol:
                        description:
                        - The protocol used for leaking from the global routing table.
                        required: true
                        default: null
                        type: str
                        choices:
                        - all
                        - static
                        - mobile
                        - connected
                        - rip
                        - odr
                    leak_to_global:
                        description:
                        - A flag indicating whether leaking to the global table is
                            enabled.
                        required: true
                        default: null
                        type: bool
            natpool:
                description:
                - A list of NAT pool configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - The identifier for the NAT pool.
                        required: true
                        default: null
                        type: int
                    prefix_length:
                        description:
                        - The length of the network prefix for the NAT pool.
                        required: false
                        default: null
                        type: int
                    range_start:
                        description:
                        - The starting IP address for the NAT pool range.
                        required: false
                        default: null
                        type: str
                    range_end:
                        description:
                        - The ending IP address for the NAT pool range.
                        required: false
                        default: null
                        type: str
                    overload:
                        description:
                        - Flag indicating whether NAT overload (PAT) is enabled for
                            the pool.
                        required: false
                        default: 'true'
                        type: str
                        choices:
                        - 'true'
                        - 'false'
                    direction:
                        description:
                        - The direction (inside or outside) associated with the NAT
                            pool.
                        required: true
                        default: null
                        type: str
                        choices:
                        - inside
                        - outside
                    tracker_id:
                        description:
                        - The tracker identifier associated with the NAT pool.
                        required: false
                        default: null
                        type: int
            static:
                description:
                - A list of static configurations within the VPN instance for NAT.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    pool_name:
                        description:
                        - The identifier for the NAT pool associated with the static
                            NAT rule.
                        required: false
                        default: null
                        type: int
                    source_ip:
                        description:
                        - The original source IP address to be translated by static
                            NAT.
                        required: false
                        default: null
                        type: str
                    translate_ip:
                        description:
                        - The translated IP address used by static NAT.
                        required: false
                        default: null
                        type: str
                    static_nat_direction:
                        description:
                        - The direction (inside or outside) for the static NAT rule.
                        required: true
                        default: null
                        type: str
                        choices:
                        - inside
                        - outside
                    tracker_id:
                        description:
                        - The tracker identifier associated with the static NAT rule.
                        required: false
                        default: null
                        type: int
            subnet_static:
                description:
                - A list of subnet-specific static configurations within the VPN instance
                    for NAT.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    source_ip_subnet:
                        description:
                        - The original source IP subnet to be translated by static
                            NAT.
                        required: true
                        default: null
                        type: str
                    translate_ip_subnet:
                        description:
                        - The translated IP subnet used by static NAT.
                        required: true
                        default: null
                        type: str
                    prefix_length:
                        description:
                        - The prefix length for the translated IP subnet in static
                            NAT.
                        required: true
                        default: null
                        type: int
                    static_nat_direction:
                        description:
                        - The direction (inside or outside) for the subnet static
                            NAT rule.
                        required: true
                        default: null
                        type: str
                        choices:
                        - inside
                        - outside
                    tracker_id:
                        description:
                        - The tracker identifier associated with the subnet static
                            NAT rule.
                        required: false
                        default: null
                        type: int
            port_forward:
                description:
                - A list of port forwarding configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    pool_name:
                        description:
                        - The identifier for the NAT pool associated with the port
                            forwarding rule.
                        required: false
                        default: null
                        type: int
                    source_port:
                        description:
                        - The source port number for the port forwarding rule.
                        required: true
                        default: null
                        type: int
                    translate_port:
                        description:
                        - The destination port number to which the source port is
                            translated.
                        required: true
                        default: null
                        type: int
                    source_ip:
                        description:
                        - The source IP address for the port forwarding rule.
                        required: true
                        default: null
                        type: str
                    translate_ip:
                        description:
                        - The destination IP address to which the source IP is translated.
                        required: true
                        default: null
                        type: str
                    proto:
                        description:
                        - The protocol used in the port forwarding rule (TCP/UDP).
                        required: true
                        default: null
                        type: str
                        choices:
                        - tcp
                        - udp
            route_import:
                description:
                - A list of route import configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    protocol:
                        description:
                        - The protocol from which routes are to be imported.
                        required: true
                        default: null
                        type: str
                        choices:
                        - static
                        - connected
                        - bgp
                        - ospf
                    protocol_sub_type:
                        description:
                        - The list of subtypes for the import protocol.
                        required: true
                        default: null
                        type: list
                        elements: str
                        choices:
                        - external
                    route_policy:
                        description:
                        - The route policy that specifies the conditions for route
                            import.
                        required: false
                        default: null
                        type: str
                    redistribute:
                        description:
                        - A list of redistribute configurations that define how routes
                            from other protocols are imported.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            protocol:
                                description:
                                - The protocol from which routes are to be redistributed.
                                required: true
                                default: null
                                type: str
                                choices:
                                - bgp
                                - eigrp
                                - ospf
                            route_policy:
                                description:
                                - The route policy that specifies the conditions for
                                    route redistribution.
                                required: false
                                default: null
                                type: str
            route_import_from:
                description:
                - A list of configurations specifying routes to import from other
                    sources into the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    source_vpn:
                        description:
                        - The VPN instance (VRF) from which routes are to be imported.
                        required: true
                        default: null
                        type: int
                    protocol:
                        description:
                        - The routing protocol from which routes are to be imported.
                        required: true
                        default: null
                        type: str
                        choices:
                        - static
                        - connected
                        - bgp
                        - ospf
                        - eigrp
                    protocol_sub_type:
                        description:
                        - The list of protocol subtypes for route importation.
                        required: true
                        default: null
                        type: list
                        elements: str
                        choices:
                        - external
                    route_policy:
                        description:
                        - The route policy that specifies the criteria for route importation.
                        required: false
                        default: null
                        type: str
                    redistribute:
                        description:
                        - A list of route redistribution configurations specifying
                            how routes from other protocols are imported.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            protocol:
                                description:
                                - The protocol from which routes are to be redistributed
                                    into the local routing table.
                                required: true
                                default: null
                                type: str
                                choices:
                                - bgp
                                - eigrp
                                - ospf
                            route_policy:
                                description:
                                - The route policy that defines the conditions for
                                    route redistribution.
                                required: false
                                default: null
                                type: str
            route_export:
                description:
                - A list of route export configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    protocol:
                        description:
                        - The routing protocol to which routes are to be exported.
                        required: true
                        default: null
                        type: str
                        choices:
                        - static
                        - connected
                        - bgp
                        - eigrp
                        - ospf
                    protocol_sub_type:
                        description:
                        - The list of protocol subtypes for route exportation.
                        required: true
                        default: null
                        type: list
                        elements: str
                        choices:
                        - external
                    route_policy:
                        description:
                        - The route policy that specifies the criteria for route exportation.
                        required: false
                        default: null
                        type: str
                    redistribute:
                        description:
                        - A list of route redistribution configurations specifying
                            how routes from other protocols are exported.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            protocol:
                                description:
                                - The protocol from which routes are to be redistributed
                                    out of the local routing table.
                                required: true
                                default: null
                                type: str
                                choices:
                                - bgp
                                - ospf
                            route_policy:
                                description:
                                - The route policy that defines the conditions for
                                    route redistribution.
                                required: false
                                default: null
                                type: str
    """
