#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    system_vsmart:
        description: Security settings for vSmart controller
        type: dict
        suboptions:
            timezone:
                description:
                - The timezone setting for the vSmart controller
                required: false
                default: UTC
                type: str
                choices:
                - Europe/Andorra
                - Asia/Dubai
                - Asia/Kabul
                - America/Antigua
                - America/Anguilla
                - Europe/Tirane
                - Asia/Yerevan
                - Africa/Luanda
                - Antarctica/McMurdo
                - Antarctica/Rothera
                - Antarctica/Palmer
                - Antarctica/Mawson
                - Antarctica/Davis
                - Antarctica/Casey
                - Antarctica/Vostok
                - Antarctica/DumontDUrville
                - Antarctica/Syowa
                - America/Argentina/Buenos_Aires
                - America/Argentina/Cordoba
                - America/Argentina/Salta
                - America/Argentina/Jujuy
                - America/Argentina/Tucuman
                - America/Argentina/Catamarca
                - America/Argentina/La_Rioja
                - America/Argentina/San_Juan
                - America/Argentina/Mendoza
                - America/Argentina/San_Luis
                - America/Argentina/Rio_Gallegos
                - America/Argentina/Ushuaia
                - Pacific/Pago_Pago
                - Europe/Vienna
                - Australia/Lord_Howe
                - Antarctica/Macquarie
                - Australia/Hobart
                - Australia/Currie
                - Australia/Melbourne
                - Australia/Sydney
                - Australia/Broken_Hill
                - Australia/Brisbane
                - Australia/Lindeman
                - Australia/Adelaide
                - Australia/Darwin
                - Australia/Perth
                - Australia/Eucla
                - America/Aruba
                - Europe/Mariehamn
                - Asia/Baku
                - Europe/Sarajevo
                - America/Barbados
                - Asia/Dhaka
                - Europe/Brussels
                - Africa/Ouagadougou
                - Europe/Sofia
                - Asia/Bahrain
                - Africa/Bujumbura
                - Africa/Porto-Novo
                - America/St_Barthelemy
                - Atlantic/Bermuda
                - Asia/Brunei
                - America/La_Paz
                - America/Kralendijk
                - America/Noronha
                - America/Belem
                - America/Fortaleza
                - America/Recife
                - America/Araguaina
                - America/Maceio
                - America/Bahia
                - America/Sao_Paulo
                - America/Campo_Grande
                - America/Cuiaba
                - America/Santarem
                - America/Porto_Velho
                - America/Boa_Vista
                - America/Manaus
                - America/Eirunepe
                - America/Rio_Branco
                - America/Nassau
                - Asia/Thimphu
                - Africa/Gaborone
                - Europe/Minsk
                - America/Belize
                - America/St_Johns
                - America/Halifax
                - America/Glace_Bay
                - America/Moncton
                - America/Goose_Bay
                - America/Blanc-Sablon
                - America/Toronto
                - America/Nipigon
                - America/Thunder_Bay
                - America/Iqaluit
                - America/Pangnirtung
                - America/Resolute
                - America/Atikokan
                - America/Rankin_Inlet
                - America/Winnipeg
                - America/Rainy_River
                - America/Regina
                - America/Swift_Current
                - America/Edmonton
                - America/Cambridge_Bay
                - America/Yellowknife
                - America/Inuvik
                - America/Creston
                - America/Dawson_Creek
                - America/Vancouver
                - America/Whitehorse
                - America/Dawson
                - Indian/Cocos
                - Africa/Kinshasa
                - Africa/Lubumbashi
                - Africa/Bangui
                - Africa/Brazzaville
                - Europe/Zurich
                - Africa/Abidjan
                - Pacific/Rarotonga
                - America/Santiago
                - Pacific/Easter
                - Africa/Douala
                - Asia/Shanghai
                - Asia/Harbin
                - Asia/Chongqing
                - Asia/Urumqi
                - Asia/Kashgar
                - America/Bogota
                - America/Costa_Rica
                - America/Havana
                - Atlantic/Cape_Verde
                - America/Curacao
                - Indian/Christmas
                - Asia/Nicosia
                - Europe/Prague
                - Europe/Berlin
                - Europe/Busingen
                - Africa/Djibouti
                - Europe/Copenhagen
                - America/Dominica
                - America/Santo_Domingo
                - Africa/Algiers
                - America/Guayaquil
                - Pacific/Galapagos
                - Europe/Tallinn
                - Africa/Cairo
                - Africa/El_Aaiun
                - Africa/Asmara
                - Europe/Madrid
                - Africa/Ceuta
                - Atlantic/Canary
                - Africa/Addis_Ababa
                - Europe/Helsinki
                - Pacific/Fiji
                - Atlantic/Stanley
                - Pacific/Chuuk
                - Pacific/Pohnpei
                - Pacific/Kosrae
                - Atlantic/Faroe
                - Europe/Paris
                - Africa/Libreville
                - Europe/London
                - America/Grenada
                - Asia/Tbilisi
                - America/Cayenne
                - Europe/Guernsey
                - Africa/Accra
                - Europe/Gibraltar
                - America/Godthab
                - America/Danmarkshavn
                - America/Scoresbysund
                - America/Thule
                - Africa/Banjul
                - Africa/Conakry
                - America/Guadeloupe
                - Africa/Malabo
                - Europe/Athens
                - Atlantic/South_Georgia
                - America/Guatemala
                - Pacific/Guam
                - Africa/Bissau
                - America/Guyana
                - Asia/Hong_Kong
                - America/Tegucigalpa
                - Europe/Zagreb
                - America/Port-au-Prince
                - Europe/Budapest
                - Asia/Jakarta
                - Asia/Pontianak
                - Asia/Makassar
                - Asia/Jayapura
                - Europe/Dublin
                - Asia/Jerusalem
                - Europe/Isle_of_Man
                - Asia/Kolkata
                - Indian/Chagos
                - Asia/Baghdad
                - Asia/Tehran
                - Atlantic/Reykjavik
                - Europe/Rome
                - Europe/Jersey
                - America/Jamaica
                - Asia/Amman
                - Asia/Tokyo
                - Africa/Nairobi
                - Asia/Bishkek
                - Asia/Phnom_Penh
                - Pacific/Tarawa
                - Pacific/Enderbury
                - Pacific/Kiritimati
                - Indian/Comoro
                - America/St_Kitts
                - Asia/Pyongyang
                - Asia/Seoul
                - Asia/Kuwait
                - America/Cayman
                - Asia/Almaty
                - Asia/Qyzylorda
                - Asia/Aqtobe
                - Asia/Aqtau
                - Asia/Oral
                - Asia/Vientiane
                - Asia/Beirut
                - America/St_Lucia
                - Europe/Vaduz
                - Asia/Colombo
                - Africa/Monrovia
                - Africa/Maseru
                - Europe/Vilnius
                - Europe/Luxembourg
                - Europe/Riga
                - Africa/Tripoli
                - Africa/Casablanca
                - Europe/Monaco
                - Europe/Chisinau
                - Europe/Podgorica
                - America/Marigot
                - Indian/Antananarivo
                - Pacific/Majuro
                - Pacific/Kwajalein
                - Europe/Skopje
                - Africa/Bamako
                - Asia/Rangoon
                - Asia/Ulaanbaatar
                - Asia/Hovd
                - Asia/Choibalsan
                - Asia/Macau
                - Pacific/Saipan
                - America/Martinique
                - Africa/Nouakchott
                - America/Montserrat
                - Europe/Malta
                - Indian/Mauritius
                - Indian/Maldives
                - Africa/Blantyre
                - America/Mexico_City
                - America/Cancun
                - America/Merida
                - America/Monterrey
                - America/Matamoros
                - America/Mazatlan
                - America/Chihuahua
                - America/Ojinaga
                - America/Hermosillo
                - America/Tijuana
                - America/Santa_Isabel
                - America/Bahia_Banderas
                - Asia/Kuala_Lumpur
                - Asia/Kuching
                - Africa/Maputo
                - Africa/Windhoek
                - Pacific/Noumea
                - Africa/Niamey
                - Pacific/Norfolk
                - Africa/Lagos
                - America/Managua
                - Europe/Amsterdam
                - Europe/Oslo
                - Asia/Kathmandu
                - Pacific/Nauru
                - Pacific/Niue
                - Pacific/Auckland
                - Pacific/Chatham
                - Asia/Muscat
                - America/Panama
                - America/Lima
                - Pacific/Tahiti
                - Pacific/Marquesas
                - Pacific/Gambier
                - Pacific/Port_Moresby
                - Asia/Manila
                - Asia/Karachi
                - Europe/Warsaw
                - America/Miquelon
                - Pacific/Pitcairn
                - America/Puerto_Rico
                - Asia/Gaza
                - Asia/Hebron
                - Europe/Lisbon
                - Atlantic/Madeira
                - Atlantic/Azores
                - Pacific/Palau
                - America/Asuncion
                - Asia/Qatar
                - Indian/Reunion
                - Europe/Bucharest
                - Europe/Belgrade
                - Europe/Kaliningrad
                - Europe/Moscow
                - Europe/Volgograd
                - Europe/Samara
                - Asia/Yekaterinburg
                - Asia/Omsk
                - Asia/Novosibirsk
                - Asia/Novokuznetsk
                - Asia/Krasnoyarsk
                - Asia/Irkutsk
                - Asia/Yakutsk
                - Asia/Khandyga
                - Asia/Vladivostok
                - Asia/Sakhalin
                - Asia/Ust-Nera
                - Asia/Magadan
                - Asia/Kamchatka
                - Asia/Anadyr
                - Africa/Kigali
                - Asia/Riyadh
                - Pacific/Guadalcanal
                - Indian/Mahe
                - Africa/Khartoum
                - Europe/Stockholm
                - Asia/Singapore
                - Atlantic/St_Helena
                - Europe/Ljubljana
                - Arctic/Longyearbyen
                - Europe/Bratislava
                - Africa/Freetown
                - Europe/San_Marino
                - Africa/Dakar
                - Africa/Mogadishu
                - America/Paramaribo
                - Africa/Juba
                - Africa/Sao_Tome
                - America/El_Salvador
                - America/Lower_Princes
                - Asia/Damascus
                - Africa/Mbabane
                - America/Grand_Turk
                - Africa/Ndjamena
                - Indian/Kerguelen
                - Africa/Lome
                - Asia/Bangkok
                - Asia/Dushanbe
                - Pacific/Fakaofo
                - Asia/Dili
                - Asia/Ashgabat
                - Africa/Tunis
                - Pacific/Tongatapu
                - Europe/Istanbul
                - America/Port_of_Spain
                - Pacific/Funafuti
                - Asia/Taipei
                - Africa/Dar_es_Salaam
                - Europe/Kiev
                - Europe/Uzhgorod
                - Europe/Zaporozhye
                - Europe/Simferopol
                - Africa/Kampala
                - Pacific/Johnston
                - Pacific/Midway
                - Pacific/Wake
                - America/New_York
                - America/Detroit
                - America/Kentucky/Louisville
                - America/Kentucky/Monticello
                - America/Indiana/Indianapolis
                - America/Indiana/Vincennes
                - America/Indiana/Winamac
                - America/Indiana/Marengo
                - America/Indiana/Petersburg
                - America/Indiana/Vevay
                - America/Chicago
                - America/Indiana/Tell_City
                - America/Indiana/Knox
                - America/Menominee
                - America/North_Dakota/Center
                - America/North_Dakota/New_Salem
                - America/North_Dakota/Beulah
                - America/Denver
                - America/Boise
                - America/Phoenix
                - America/Los_Angeles
                - America/Anchorage
                - America/Juneau
                - America/Sitka
                - America/Yakutat
                - America/Nome
                - America/Adak
                - America/Metlakatla
                - Pacific/Honolulu
                - America/Montevideo
                - Asia/Samarkand
                - Asia/Tashkent
                - Europe/Vatican
                - America/St_Vincent
                - America/Caracas
                - America/Tortola
                - America/St_Thomas
                - Asia/Ho_Chi_Minh
                - Pacific/Efate
                - Pacific/Wallis
                - Pacific/Apia
                - Asia/Aden
                - Indian/Mayotte
                - Africa/Johannesburg
                - Africa/Lusaka
                - Africa/Harare
                - UTC
            host_name:
                description:
                - The hostname for the vSmart controller
                required: false
                type: raw
                suboptions:
                    name:
                        default: system_host_name
                        required: true
                        type: str
                        description: Device Specific Variables name
            dual_stack_ipv6:
                description:
                - Enable Dual Stack IPv6 Default
                required: false
                type: raw
                suboptions:
                    name:
                        default: system_ipv6-strict-control
                        required: true
                        type: str
                        description: Device Specific Variables name
            description:
                description:
                - Set a text description of the device
                required: false
                default: null
                type: str
            location:
                description:
                - A description of the physical location of the vSmart controller
                required: false
                default: null
                type: str
            system_tunnel_mtu:
                description:
                - MTU size for system tunnels
                required: false
                default: null
                type: int
            latitude:
                description:
                - Geographical latitude of the vSmart controller
                required: false
                default: null
                type: int
            longitude:
                description:
                - Geographical longitude of the vSmart controller
                required: false
                default: null
                type: int
            device_groups:
                description:
                - Device group names for the vSmart controller
                required: false
                default: null
                type: list
                elements: str
            system_ip:
                description:
                - System IP address for the vSmart controller
                required: false
                type: raw
                suboptions:
                    name:
                        default: system_system_ip
                        required: true
                        type: str
                        description: Device Specific Variables name
            site_id:
                description:
                - Site ID for the vSmart controller
                required: false
                type: raw
                suboptions:
                    name:
                        default: system_site_id
                        required: true
                        type: str
                        description: Device Specific Variables name
            overlay_id:
                description:
                - Overlay ID for the vSmart controller
                required: false
                default: null
                type: int
            topology:
                description:
                - Set the topology
                required: false
                default: null
                type: list
                elements: str
                choices:
                - hub-and-spoke
            port_offset:
                description:
                - Port offset for port hopping
                required: false
                default: null
                type: int
            port_hop:
                description:
                - Enable or disable port hopping
                required: false
                default: null
                type: bool
            control_session_pps:
                description:
                - Control session packets per second limit
                required: false
                default: null
                type: int
            controller_group_id:
                description:
                - Group ID for the vSmart controller
                required: false
                default: null
                type: int
            track_transport:
                description:
                - Enable or disable tracking of transport connections
                required: false
                default: true
                type: bool
            track_default_gateway:
                description:
                - Enable or disable tracking of the default gateway
                required: false
                default: true
                type: bool
            iptables_enable:
                description:
                - Enable or disable iptables for security
                required: false
                default: true
                type: bool
            admin_tech_on_failure:
                description:
                - Enable automatic generation of tech-support file on failure
                required: false
                default: true
                type: bool
            idle_timeout:
                description:
                - Idle timeout in minutes for user sessions
                required: false
                default: null
                type: int
            dns_cache_timeout:
                description:
                - DNS cache timeout in minutes
                required: false
                default: null
                type: int
            region_list_id:
                description:
                - Configure a list of region ID
                required: false
                default: null
                type: int
            management_region:
                description:
                - Management Region
                required: false
                default: null
                type: bool
            compatible:
                description:
                - Configure compatible TLOC color
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    color_1:
                        description:
                        - First TLOC color in comparsion
                        required: false
                        default: null
                        type: str
                        choices:
                        - default
                        - mpls
                        - metro-ethernet
                        - biz-internet
                        - public-internet
                        - lte
                        - 3g
                        - red
                        - green
                        - blue
                        - gold
                        - silver
                        - bronze
                        - custom1
                        - custom2
                        - custom3
                        - private1
                        - private2
                        - private3
                        - private4
                        - private5
                        - private6
                    color_2:
                        description:
                        - Second TLOC color in comparsion
                        required: false
                        default: null
                        type: str
                        choices:
                        - default
                        - mpls
                        - metro-ethernet
                        - biz-internet
                        - public-internet
                        - lte
                        - 3g
                        - red
                        - green
                        - blue
                        - gold
                        - silver
                        - bronze
                        - custom1
                        - custom2
                        - custom3
                        - private1
                        - private2
                        - private3
                        - private4
                        - private5
                        - private6
            incompatible:
                description:
                - Configure incompatible TLOC color
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    color_1:
                        description:
                        - First TLOC color in comparsion
                        required: false
                        default: null
                        type: str
                        choices:
                        - default
                        - mpls
                        - metro-ethernet
                        - biz-internet
                        - public-internet
                        - lte
                        - 3g
                        - red
                        - green
                        - blue
                        - gold
                        - silver
                        - bronze
                        - custom1
                        - custom2
                        - custom3
                        - private1
                        - private2
                        - private3
                        - private4
                        - private5
                        - private6
                    color_2:
                        description:
                        - Second TLOC color in comparsion
                        required: false
                        default: null
                        type: str
                        choices:
                        - default
                        - mpls
                        - metro-ethernet
                        - biz-internet
                        - public-internet
                        - lte
                        - 3g
                        - red
                        - green
                        - blue
                        - gold
                        - silver
                        - bronze
                        - custom1
                        - custom2
                        - custom3
                        - private1
                        - private2
                        - private3
                        - private4
                        - private5
                        - private6
    """
