#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    cisco_ospf:
        description: Cisco OSPF (Open Shortest Path First) configuration
        type: dict
        suboptions:
            router_id:
                description:
                - The router ID of the OSPF process.
                required: false
                default: null
                type: str
            reference_bandwidth:
                description:
                - The reference bandwidth used by OSPF for cost calculation.
                required: false
                default: null
                type: str
            rfc1583:
                description:
                - Compatibility switch for RFC 1583.
                required: false
                default: null
                type: str
            originate:
                description:
                - Controls the origination of default information into the OSPF domain.
                required: false
                default: null
                type: str
            always:
                description:
                - Ensures that the default route is always advertised, regardless
                    of the existence of a default route in the routing table.
                required: false
                default: null
                type: str
            metric:
                description:
                - The metric value to be set for the default route advertised by OSPF.
                required: false
                default: null
                type: str
            metric_type:
                description:
                - The metric type (Type 1 or Type 2) for OSPF external routes.
                required: false
                default: null
                type: str
                choices:
                - type1
                - type2
            external:
                description:
                - The OSPF external route metric.
                required: false
                default: null
                type: str
            inter_area:
                description:
                - The OSPF inter-area route metric.
                required: false
                default: null
                type: str
            intra_area:
                description:
                - The OSPF intra-area route metric.
                required: false
                default: null
                type: str
            delay:
                description:
                - The OSPF Shortest Path First (SPF) delay time.
                required: false
                default: null
                type: str
            initial_hold:
                description:
                - The initial hold time between consecutive SPF calculations.
                required: false
                default: null
                type: str
            max_hold:
                description:
                - The maximum hold time between consecutive SPF calculations.
                required: false
                default: null
                type: str
            redistribute:
                description:
                - A list of OSPF redistribution configurations.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    protocol:
                        description:
                        - The routing protocol from which routes are to be redistributed
                            into OSPF.
                        required: true
                        default: null
                        type: str
                        choices:
                        - static
                        - connected
                        - bgp
                        - omp
                        - nat
                        - eigrp
                    route_policy:
                        description:
                        - Name of the route policy to control the redistribution.
                        required: false
                        default: null
                        type: str
                    dia:
                        description:
                        - Default information originate, which controls the advertisement
                            of default route.
                        required: false
                        default: null
                        type: str
            router_lsa:
                description:
                - Configuration options for the Router LSA in OSPF.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    ad_type:
                        description:
                        - Type of advertisement for the router LSA.
                        required: true
                        default: null
                        type: str
                        choices:
                        - administrative
                        - on-startup
                    time:
                        description:
                        - Time in seconds for advertisement.
                        required: true
                        default: null
                        type: str
            route_policy:
                description:
                - A list of OSPF route policies.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    direction:
                        description:
                        - Direction of the route policy (e.g., 'in' for incoming).
                        required: true
                        default: null
                        type: str
                        choices:
                        - in
                    pol_name:
                        description:
                        - Name of the route policy.
                        required: true
                        default: null
                        type: str
            area:
                description:
                - A list of OSPF areas and their configurations.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    a_num:
                        description:
                        - The OSPF area number.
                        required: true
                        default: null
                        type: str
                    stub:
                        description:
                        - Configuration for the OSPF area to be a stub area. If set,
                            no-summary can be applied.
                        required: false
                        default: null
                        type: str
                    nssa:
                        description:
                        - Configuration for the OSPF area to be a Not-So-Stubby Area
                            (NSSA). If set, no-summary can be applied.
                        required: false
                        default: null
                        type: str
                    interface:
                        description:
                        - A list of OSPF interface configurations associated with
                            this area.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            name:
                                description:
                                - The name of the OSPF interface.
                                required: true
                                default: null
                                type: str
                            hello_interval:
                                description:
                                - The interval between the OSPF Hello packets that
                                    the router sends on the interface.
                                required: false
                                default: null
                                type: str
                            dead_interval:
                                description:
                                - The time interval an OSPF router waits for a Hello
                                    packet before declaring the sending router down.
                                required: false
                                default: null
                                type: str
                            retransmit_interval:
                                description:
                                - The interval between LSA retransmissions for adjacencies
                                    belonging to the interface.
                                required: false
                                default: null
                                type: str
                            cost:
                                description:
                                - The OSPF cost (metric) for this interface.
                                required: false
                                default: null
                                type: str
                            priority:
                                description:
                                - The OSPF priority of the interface.
                                required: false
                                default: null
                                type: str
                            network:
                                description:
                                - The OSPF network type for the interface.
                                required: false
                                default: broadcast
                                type: str
                                choices:
                                - broadcast
                                - point-to-point
                                - non-broadcast
                                - point-to-multipoint
                            passive_interface:
                                description:
                                - Whether the interface is a passive OSPF interface.
                                required: false
                                default: null
                                type: str
                            type:
                                description:
                                - The OSPF authentication type for the interface.
                                required: false
                                default: null
                                type: str
                                choices:
                                - simple
                                - message-digest
                                - 'null'
                            message_digest_key:
                                description:
                                - The message-digest key ID for OSPF authentication.
                                required: false
                                default: null
                                type: str
                            md5:
                                description:
                                - The MD5 string for OSPF message-digest authentication.
                                required: false
                                default: null
                                type: str
                    range:
                        description:
                        - A list of OSPF range entries to be associated with this
                            area.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            address:
                                description:
                                - The IPv4 network address to be advertised as an
                                    OSPF range.
                                required: true
                                default: null
                                type: str
                            cost:
                                description:
                                - The OSPF cost (metric) for this range.
                                required: false
                                default: null
                                type: str
                            no_advertise:
                                description:
                                - Whether to suppress advertising this range.
                                required: false
                                default: null
                                type: str
    """
