#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    cisco_ntp:
        description: Cisco NTP Feature Template configuration
        type: dict
        suboptions:
            server:
                description:
                - List of NTP servers
                required: false
                default: []
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - The hostname or IP address of the NTP server
                        required: true
                        default: null
                        type: str
                    key:
                        description:
                        - The identifier for the authentication key
                        required: false
                        default: null
                        type: int
                    vpn:
                        description:
                        - The VPN ID associated with the NTP server
                        required: false
                        default: null
                        type: int
                    version:
                        description:
                        - The NTP version used
                        required: false
                        default: null
                        type: int
                    source_interface:
                        description:
                        - The source interface for NTP messages
                        required: false
                        default: null
                        type: str
                    prefer:
                        description:
                        - Whether this server is preferred over others
                        required: false
                        default: null
                        type: bool
            authentication:
                description:
                - List of authentication keys
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    number:
                        description:
                        - The authentication key number
                        required: true
                        default: null
                        type: int
                    md5:
                        description:
                        - The MD5 hash used for authentication
                        required: true
                        default: null
                        type: str
            trusted:
                description:
                - List of trusted key numbers
                required: false
                default: null
                type: list
                elements: int
            enable:
                description:
                - Whether the device is an NTP master
                required: false
                default: null
                type: bool
            stratum:
                description:
                - The stratum level if the device is an NTP master
                required: false
                default: null
                type: int
            source:
                description:
                - The source interface for NTP messages if the device is an NTP master
                required: false
                default: null
                type: str
    """
