#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    vpn_vsmart:
        description: vSmart VPN Feature Template configuration.
        type: dict
        suboptions:
            vpn_id:
                description:
                - The unique identifier for the VPN, only 0 and 512 are allowed on
                    vsmart
                required: true
                default: null
                type: str
                choices:
                - '0'
                - '512'
            name:
                description:
                - The name of the VPN.
                required: false
                default: null
                type: str
            dns:
                description:
                - A list of DNS configurations for the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    dns_addr:
                        description:
                        - The IP address of the DNS server.
                        required: false
                        default: null
                        type: str
                    role:
                        description:
                        - The role of the DNS server, either 'PRIMARY' or 'SECONDARY'.
                        required: true
                        default: null
                        type: str
                        choices:
                        - primary
                        - secondary
            host:
                description:
                - Static DNS mapping
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    hostname:
                        description:
                        - The hostname of the device.
                        required: true
                        default: null
                        type: str
                    ip:
                        description:
                        - A list of IP addresses associated with the hostname.
                        required: true
                        default: null
                        type: list
                        elements: str
            route_v4:
                description:
                - A list of IPv4 route configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    prefix:
                        description:
                        - The IPv4 network prefix for the static route.
                        required: false
                        default: null
                        type: str
                    next_hop:
                        description:
                        - A list of IPv4 next hops for the route.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            address:
                                description:
                                - The IP address of the next hop for the route.
                                required: false
                                default: null
                                type: str
                            distance:
                                description:
                                - The administrative distance of the next hop.
                                required: false
                                default: null
                                type: int
                    route_interface:
                        description:
                        - The interface configuration for the IPv4 static route.
                        required: false
                        default: null
                        type: dict
                        elements: dict
                        suboptions:
                            interface_name:
                                description:
                                - The name of the interface used for routing.
                                required: true
                                default: null
                                type: str
                            interface_next_hop:
                                description:
                                - A list of next hops associated with the interface
                                    for routing purposes.
                                required: false
                                default: null
                                type: list
                                elements: dict
                                suboptions:
                                    address:
                                        description:
                                        - The IP address of the next hop for the route.
                                        required: false
                                        default: null
                                        type: str
                                    distance:
                                        description:
                                        - The administrative distance of the next
                                            hop.
                                        required: false
                                        default: null
                                        type: int
                    null0:
                        description:
                        - A flag indicating whether to route traffic to null0 for
                            this static route.
                        required: false
                        default: null
                        type: bool
                    distance:
                        description:
                        - The administrative distance for the static route.
                        required: false
                        default: null
                        type: int
                    vpn:
                        description:
                        - The VPN instance identifier associated with the static route.
                        required: false
                        default: null
                        type: int
            route_v6:
                description:
                - A list of IPv6 route configurations within the VPN instance.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    prefix:
                        description:
                        - The IPv6 network prefix for the static route.
                        required: true
                        default: null
                        type: str
                    next_hop:
                        description:
                        - A list of IPv6 next hops for the route.
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            address:
                                description:
                                - The IPv6 address of the next hop for the route.
                                required: true
                                default: null
                                type: str
                            distance:
                                description:
                                - The administrative distance of the IPv6 next hop.
                                required: false
                                default: null
                                type: int
                    null0:
                        description:
                        - A flag indicating whether to route IPv6 traffic to null0
                            for this static route.
                        required: false
                        default: null
                        type: bool
                    distance:
                        description:
                        - The administrative distance for the static route.
                        required: false
                        default: null
                        type: int
                    vpn:
                        description:
                        - The VPN instance identifier associated with the static route.
                        required: false
                        default: null
                        type: int
    """
