#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    vpn_vsmart_interface:
        description: vSmart VPN Interface Feature Template configuration
        type: dict
        suboptions:
            if_name:
                description:
                - The name of the interface.
                required: false
                default: null
                type: str
            interface_description:
                description:
                - A description for the interface.
                required: false
                default: null
                type: str
            ipv4_address:
                description:
                - The primary IPv4 address assigned to the interface.
                required: false
                default: null
                type: str
            dhcp_ipv4_client:
                description:
                - Whether DHCP client is enabled on the interface for IPv4 addressing.
                    True if enabled, False otherwise.
                required: false
                default: null
                type: bool
            dhcp_distance:
                description:
                - Administrative distance for DHCP routes on the interface.
                required: false
                default: null
                type: int
            ipv6_address:
                description:
                - The primary IPv6 address assigned to the interface.
                required: false
                default: null
                type: str
            dhcp_ipv6_client:
                description:
                - Whether DHCP client is enabled on the interface for IPv6 addressing.
                    True if enabled, False otherwise.
                required: false
                default: null
                type: bool
            dhcp_ipv6_distance:
                description:
                - Administrative distance for DHCP routes on the interface.
                required: false
                default: null
                type: int
            dhcp_rapid_commit:
                description:
                - Enable DHCPv6 rapid commit
                required: false
                default: null
                type: bool
            group:
                description:
                - Identifies the group or groups the interface belongs to.
                required: false
                default: null
                type: list
                elements: int
            value:
                description:
                - The value field often corresponds to a specific attribute or setting,
                    such as color in this context.
                required: false
                default: null
                type: str
                choices:
                - default
                - mpls
                - metro-ethernet
                - biz-internet
                - public-internet
                - lte
                - 3g
                - red
                - green
                - blue
                - gold
                - silver
                - bronze
                - custom1
                - custom2
                - custom3
                - private1
                - private2
                - private3
                - private4
                - private5
                - private6
            carrier:
                description:
                - Specifies the carrier information for the tunnel interface.
                required: false
                default: null
                type: str
                choices:
                - default
                - carrier1
                - carrier2
                - carrier3
                - carrier4
                - carrier5
                - carrier6
                - carrier7
                - carrier8
            nat_refresh_interval:
                description:
                - Interval in seconds to refresh NAT (Network Address Translation)
                    mappings.
                required: false
                default: null
                type: int
            hello_interval:
                description:
                - Time interval in seconds between successive hello packets sent over
                    the tunnel interface.
                required: false
                default: null
                type: int
            hello_tolerance:
                description:
                - Time in seconds to wait before declaring a neighbor down due to
                    missing hello packets.
                required: false
                default: null
                type: int
            all:
                description:
                - Permits or denies all services through the tunnel interface.
                required: false
                default: null
                type: bool
            dhcp:
                description:
                - Enables or disables Dynamic Host Configuration Protocol (DHCP) on
                    the tunnel interface.
                required: false
                default: null
                type: bool
            dns:
                description:
                - Allows or disallows Domain Name System (DNS) queries through the
                    tunnel interface.
                required: false
                default: null
                type: bool
            icmp:
                description:
                - Enables or disables Internet Control Message Protocol (ICMP) for
                    ping and traceroute through the tunnel interface.
                required: false
                default: null
                type: bool
            sshd:
                description:
                - Allows or disallows Secure Shell (SSH) daemon access through the
                    tunnel interface.
                required: false
                default: null
                type: bool
            netconf:
                description:
                - Enables or disables NETCONF protocol support on the tunnel interface.
                required: false
                default: null
                type: bool
            ntp:
                description:
                - Allows or disallows Network Time Protocol (NTP) synchronization
                    through the tunnel interface.
                required: false
                default: null
                type: bool
            stun:
                description:
                - Enables or disables Session Traversal Utilities for NAT (STUN) on
                    the tunnel interface.
                required: false
                default: null
                type: bool
            flow_control:
                description:
                - Enable flow control.
                required: false
                default: null
                type: str
                choices:
                - ingress
                - egress
                - autoneg
                - both
                - none
            clear_dont_fragment:
                description:
                - Enables Clear don't fragment bit
                required: false
                default: false
                type: bool
            autonegotiate:
                description:
                - Link autonegotiation
                required: false
                default: true
                type: bool
            pmtu:
                description:
                - Enables Path MTU Discovery
                required: false
                default: false
                type: bool
            mtu:
                description:
                - Interface MTU <576..2000>
                required: false
                default: null
                type: int
            tcp_mss_adjust:
                description:
                - TCP MSS on SYN packets, in bytes
                required: false
                default: null
                type: int
            mac_address:
                description:
                - Specifies the MAC address for the interface.
                required: false
                default: null
                type: str
            speed:
                description:
                - Defines the speed of the interface, such as 10Mbps, 100Mbps, or
                    1Gbps.
                required: false
                default: null
                type: str
                choices:
                - '10'
                - '100'
                - '1000'
            duplex:
                description:
                - Sets the duplex mode for the interface, such as full or half duplex.
                required: false
                default: null
                type: str
                choices:
                - full
                - half
            shutdown:
                description:
                - Enables or disables (shuts down) the interface.
                required: false
                default: false
                type: bool
            ip:
                description:
                - A list of IP configurations for Address Resolution Protocol (ARP)
                    settings.
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    addr:
                        description:
                        - IPv4 address for the interface.
                        required: true
                        default: null
                        type: str
                    mac:
                        description:
                        - MAC address associated with the IPv4 address.
                        required: true
                        default: null
                        type: str
    """
