#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# This file is autogenerated by `utils/feature_template_docs_generator.py`


from __future__ import annotations


class ModuleDocFragment(object):
    DOCUMENTATION = r"""
options:
    cisco_snmp:
        description: Cisco SNMP Feature Template configuration
        type: dict
        suboptions:
            shutdown:
                description:
                - Indicates whether SNMP is administratively shut down
                required: false
                default: true
                type: bool
            contact:
                description:
                - The contact information for the SNMP administrator
                required: false
                default: null
                type: str
            location:
                description:
                - The physical location information for the SNMP agent
                required: false
                default: null
                type: str
            view:
                description:
                - List of SNMP views for controlling access to OIDs
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - The name of the SNMP view
                        required: true
                        default: null
                        type: str
                    oid:
                        description:
                        - List of OIDs to include or exclude in the view
                        required: false
                        default: null
                        type: list
                        elements: dict
                        suboptions:
                            id:
                                description:
                                - The OID (Object Identifier) to include or exclude
                                    in the view
                                required: true
                                default: null
                                type: str
                            exclude:
                                description:
                                - Indicates whether the OID should be excluded from
                                    the view
                                required: false
                                default: null
                                type: bool
            community:
                description:
                - List of SNMP communities for different access rights
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - The name of the SNMP community
                        required: true
                        default: null
                        type: str
                    view:
                        description:
                        - The SNMP view associated with the community
                        required: true
                        default: null
                        type: str
                    authorization:
                        description:
                        - The authorization level of the community
                        required: true
                        default: null
                        type: str
                        choices:
                        - read-only
            group:
                description:
                - List of SNMP groups defining security models and access rights
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - The name of the SNMP group
                        required: true
                        default: null
                        type: str
                    security_level:
                        description:
                        - The security level associated with the group
                        required: true
                        default: null
                        type: str
                        choices:
                        - no-auth-no-priv
                        - auth-no-priv
                        - auth-priv
                    view:
                        description:
                        - The SNMP view associated with the group
                        required: true
                        default: null
                        type: str
            user:
                description:
                - List of SNMP users with authentication and privacy configurations
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    name:
                        description:
                        - The name of the SNMP user
                        required: true
                        default: null
                        type: str
                    auth:
                        description:
                        - The authentication protocol used
                        required: false
                        default: null
                        type: str
                        choices:
                        - md5
                        - sha
                    auth_password:
                        description:
                        - The password for authentication
                        required: false
                        default: null
                        type: str
                    priv:
                        description:
                        - The privacy (encryption) protocol used
                        required: false
                        default: null
                        type: str
                        choices:
                        - aes-cfb-128
                        - aes-256-cfb-128
                    priv_password:
                        description:
                        - The password for privacy
                        required: false
                        default: null
                        type: str
                    group:
                        description:
                        - The group to which the user belongs
                        required: true
                        default: null
                        type: str
            target:
                description:
                - List of SNMP targets for sending traps
                required: false
                default: null
                type: list
                elements: dict
                suboptions:
                    vpn_id:
                        description:
                        - The VPN ID where the SNMP target resides
                        required: true
                        default: null
                        type: int
                    ip:
                        description:
                        - The IP address of the SNMP target
                        required: true
                        default: null
                        type: str
                    port:
                        description:
                        - The port number for the SNMP target
                        required: true
                        default: null
                        type: int
                    community_name:
                        description:
                        - The community name for the SNMP target
                        required: false
                        default: null
                        type: str
                    user:
                        description:
                        - The user name for the SNMP target
                        required: false
                        default: null
                        type: str
                    source_interface:
                        description:
                        - The source interface for sending SNMP traps
                        required: false
                        default: null
                        type: str
    """
