aaa_definition = {
    "aaa": {
        "default": None,
        "options": {
            "accounting": {"default": False, "required": False, "type": "bool"},
            "admin_auth_order": {"default": False, "required": False, "type": "bool"},
            "audit_disable": {"default": False, "required": False, "type": "bool"},
            "auth_fallback": {"default": False, "required": False, "type": "bool"},
            "auth_order": {
                "default": ["local", "radius", "tacacs"],
                "elements": "str",
                "required": False,
                "type": "list",
            },
            "cisco_tac_ro_user": {"default": True, "required": False, "type": "bool"},
            "cisco_tac_rw_user": {"default": True, "required": False, "type": "bool"},
            "netconf_disable": {"default": False, "required": False, "type": "bool"},
            "radius_retransmit": {"default": None, "required": False, "type": "int"},
            "radius_server": {
                "default": None,
                "elements": "dict",
                "options": {
                    "acct_port": {"default": None, "required": False, "type": "int"},
                    "address": {"default": None, "required": True, "type": "str"},
                    "auth_port": {"default": None, "required": False, "type": "int"},
                    "key": {"default": None, "required": False, "type": "str"},
                    "priority": {"default": None, "required": False, "type": "int"},
                    "secret_key": {"default": None, "required": False, "type": "str"},
                    "source_interface": {"default": None, "required": False, "type": "str"},
                    "tag": {"default": None, "required": False, "type": "str"},
                    "vpn": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "radius_server_list": {"default": None, "elements": "str", "required": False, "type": "list"},
            "radius_timeout": {"default": None, "required": False, "type": "int"},
            "tacacs_authentication": {"default": "pap", "required": False, "type": "str"},
            "tacacs_server": {
                "default": None,
                "elements": "dict",
                "options": {
                    "address": {"default": None, "required": True, "type": "str"},
                    "auth_port": {"default": None, "required": False, "type": "int"},
                    "key": {"default": None, "required": False, "type": "str"},
                    "priority": {"default": None, "required": False, "type": "int"},
                    "secret_key": {"default": None, "required": False, "type": "str"},
                    "source_interface": {"default": None, "required": False, "type": "str"},
                    "vpn": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "tacacs_timeout": {"default": None, "required": False, "type": "int"},
            "task": {
                "default": None,
                "elements": "dict",
                "options": {
                    "config_accept_action": {
                        "default": None,
                        "elements": "dict",
                        "options": {"command": {"default": None, "required": True, "type": "str"}},
                        "required": False,
                        "type": "list",
                    },
                    "config_default_action": {"default": None, "required": True, "type": "str"},
                    "config_deny_action": {
                        "default": None,
                        "elements": "dict",
                        "options": {"command": {"default": None, "required": True, "type": "str"}},
                        "required": False,
                        "type": "list",
                    },
                    "name": {"default": None, "required": True, "type": "str"},
                    "oper_exec_accept_action": {
                        "default": None,
                        "elements": "dict",
                        "options": {"command": {"default": None, "required": True, "type": "str"}},
                        "required": False,
                        "type": "list",
                    },
                    "oper_exec_default_action": {"default": None, "required": True, "type": "str"},
                    "oper_exec_deny_action": {
                        "default": None,
                        "elements": "dict",
                        "options": {"command": {"default": None, "required": True, "type": "str"}},
                        "required": False,
                        "type": "list",
                    },
                    "password": {"default": None, "required": False, "type": "str"},
                    "privilege": {"default": "15", "required": False, "type": "str"},
                    "secret": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "user": {
                "default": None,
                "elements": "dict",
                "options": {
                    "description": {"default": None, "required": False, "type": "str"},
                    "group": {"default": None, "elements": "str", "required": False, "type": "list"},
                    "name": {"default": None, "required": True, "type": "str"},
                    "password": {"default": None, "required": False, "type": "str"},
                    "pubkey_chain": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "key_string": {"default": None, "required": True, "type": "str"},
                            "key_type": {"default": "ssh-rsa", "required": False, "type": "str"},
                            "usertag": {"default": None, "required": True, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "secret": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "usergroup": {
                "default": None,
                "elements": "dict",
                "options": {
                    "name": {"default": None, "required": True, "type": "str"},
                    "task": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "mode": {"default": None, "required": True, "type": "str"},
                            "permission": {"default": "pap", "elements": "str", "required": False, "type": "list"},
                        },
                        "required": False,
                        "type": "list",
                    },
                },
                "required": False,
                "type": "list",
            },
        },
        "required": False,
        "type": "dict",
    }
}
