cisco_ospf_definition = { 'cisco_ospf': { 'default': None,
                  'options': { 'always': { 'default': None,
                                           'required': False,
                                           'type': 'str'},
                               'area': { 'default': None,
                                         'elements': 'dict',
                                         'options': { 'a_num': { 'default': None,
                                                                 'required': True,
                                                                 'type': 'str'},
                                                      'interface': { 'default': None,
                                                                     'elements': 'dict',
                                                                     'options': { 'cost': { 'default': None,
                                                                                            'required': False,
                                                                                            'type': 'str'},
                                                                                  'dead_interval': { 'default': None,
                                                                                                     'required': False,
                                                                                                     'type': 'str'},
                                                                                  'hello_interval': { 'default': None,
                                                                                                      'required': False,
                                                                                                      'type': 'str'},
                                                                                  'md5': { 'default': None,
                                                                                           'required': False,
                                                                                           'type': 'str'},
                                                                                  'message_digest_key': { 'default': None,
                                                                                                          'required': False,
                                                                                                          'type': 'str'},
                                                                                  'name': { 'default': None,
                                                                                            'required': True,
                                                                                            'type': 'str'},
                                                                                  'network': { 'default': 'broadcast',
                                                                                               'required': False,
                                                                                               'type': 'str'},
                                                                                  'passive_interface': { 'default': None,
                                                                                                         'required': False,
                                                                                                         'type': 'str'},
                                                                                  'priority': { 'default': None,
                                                                                                'required': False,
                                                                                                'type': 'str'},
                                                                                  'retransmit_interval': { 'default': None,
                                                                                                           'required': False,
                                                                                                           'type': 'str'},
                                                                                  'type': { 'default': None,
                                                                                            'required': False,
                                                                                            'type': 'str'}},
                                                                     'required': False,
                                                                     'type': 'list'},
                                                      'nssa': { 'default': None,
                                                                'required': False,
                                                                'type': 'str'},
                                                      'range': { 'default': None,
                                                                 'elements': 'dict',
                                                                 'options': { 'address': { 'default': None,
                                                                                           'required': True,
                                                                                           'type': 'str'},
                                                                              'cost': { 'default': None,
                                                                                        'required': False,
                                                                                        'type': 'str'},
                                                                              'no_advertise': { 'default': None,
                                                                                                'required': False,
                                                                                                'type': 'str'}},
                                                                 'required': False,
                                                                 'type': 'list'},
                                                      'stub': { 'default': None,
                                                                'required': False,
                                                                'type': 'str'}},
                                         'required': False,
                                         'type': 'list'},
                               'delay': { 'default': None,
                                          'required': False,
                                          'type': 'str'},
                               'external': { 'default': None,
                                             'required': False,
                                             'type': 'str'},
                               'initial_hold': { 'default': None,
                                                 'required': False,
                                                 'type': 'str'},
                               'inter_area': { 'default': None,
                                               'required': False,
                                               'type': 'str'},
                               'intra_area': { 'default': None,
                                               'required': False,
                                               'type': 'str'},
                               'max_hold': { 'default': None,
                                             'required': False,
                                             'type': 'str'},
                               'metric': { 'default': None,
                                           'required': False,
                                           'type': 'str'},
                               'metric_type': { 'default': None,
                                                'required': False,
                                                'type': 'str'},
                               'originate': { 'default': None,
                                              'required': False,
                                              'type': 'str'},
                               'redistribute': { 'default': None,
                                                 'elements': 'dict',
                                                 'options': { 'dia': { 'default': None,
                                                                       'required': False,
                                                                       'type': 'str'},
                                                              'protocol': { 'default': None,
                                                                            'required': True,
                                                                            'type': 'str'},
                                                              'route_policy': { 'default': None,
                                                                                'required': False,
                                                                                'type': 'str'}},
                                                 'required': False,
                                                 'type': 'list'},
                               'reference_bandwidth': { 'default': None,
                                                        'required': False,
                                                        'type': 'str'},
                               'rfc1583': { 'default': None,
                                            'required': False,
                                            'type': 'str'},
                               'route_policy': { 'default': None,
                                                 'elements': 'dict',
                                                 'options': { 'direction': { 'default': None,
                                                                             'required': True,
                                                                             'type': 'str'},
                                                              'pol_name': { 'default': None,
                                                                            'required': True,
                                                                            'type': 'str'}},
                                                 'required': False,
                                                 'type': 'list'},
                               'router_id': { 'default': None,
                                              'required': False,
                                              'type': 'str'},
                               'router_lsa': { 'default': None,
                                               'elements': 'dict',
                                               'options': { 'ad_type': { 'default': None,
                                                                         'required': True,
                                                                         'type': 'str'},
                                                            'time': { 'default': None,
                                                                      'required': True,
                                                                      'type': 'str'}},
                                               'required': False,
                                               'type': 'list'}},
                  'required': False,
                  'type': 'dict'}}
