cisco_aaa_definition = {
    "cisco_aaa": {
        "default": None,
        "options": {
            "accounting_group": {"default": None, "required": False, "type": "bool"},
            "authentication_group": {"default": None, "required": False, "type": "bool"},
            "domain_stripping": {"default": None, "required": False, "type": "str"},
            "port": {"default": None, "required": False, "type": "str"},
            "radius": {
                "default": None,
                "elements": "dict",
                "options": {
                    "group_name": {"default": None, "required": True, "type": "str"},
                    "server": {
                        "default": [],
                        "elements": "dict",
                        "options": {
                            "acct_port": {"default": None, "required": False, "type": "str"},
                            "address": {"default": None, "required": True, "type": "str"},
                            "auth_port": {"default": None, "required": False, "type": "str"},
                            "key": {"default": None, "required": True, "type": "str"},
                            "key_enum": {"default": None, "required": False, "type": "str"},
                            "key_type": {"default": None, "required": False, "type": "str"},
                            "retransmit": {"default": None, "required": False, "type": "str"},
                            "secret_key": {"default": None, "required": False, "type": "str"},
                            "timeout": {"default": None, "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "source_interface": {"default": None, "required": True, "type": "str"},
                    "vpn": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "server_auth_order": {"default": None, "required": False, "type": "str"},
            "tacacs": {
                "default": None,
                "elements": "dict",
                "options": {
                    "group_name": {"default": None, "required": True, "type": "str"},
                    "server": {
                        "default": [],
                        "elements": "dict",
                        "options": {
                            "address": {"default": None, "required": True, "type": "str"},
                            "key": {"default": None, "required": True, "type": "str"},
                            "key_enum": {"default": None, "required": False, "type": "str"},
                            "port": {"default": None, "required": False, "type": "str"},
                            "secret_key": {"default": None, "required": False, "type": "str"},
                            "timeout": {"default": None, "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "source_interface": {"default": None, "required": False, "type": "str"},
                    "vpn": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "user": {
                "default": None,
                "elements": "dict",
                "options": {
                    "name": {"default": None, "required": True, "type": "str"},
                    "password": {"default": None, "required": False, "type": "str"},
                    "privilege": {"default": None, "required": False, "type": "str"},
                    "pubkey_chain": {"default": [], "elements": "str", "required": False, "type": "list"},
                    "secret": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
        },
        "required": False,
        "type": "dict",
    }
}
