cisco_ospf_definition = {
    "cisco_ospf": {
        "default": None,
        "options": {
            "always": {"default": None, "required": False, "type": "bool"},
            "area": {
                "default": None,
                "elements": "dict",
                "options": {
                    "a_num": {"default": None, "required": True, "type": "int"},
                    "interface": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "cost": {"default": None, "required": False, "type": "int"},
                            "dead_interval": {"default": None, "required": False, "type": "int"},
                            "hello_interval": {"default": None, "required": False, "type": "int"},
                            "md5": {"default": None, "required": False, "type": "str"},
                            "message_digest_key": {"default": None, "required": False, "type": "int"},
                            "name": {"default": None, "required": True, "type": "str"},
                            "network": {"default": "broadcast", "required": False, "type": "str"},
                            "passive_interface": {"default": False, "required": False, "type": "bool"},
                            "priority": {"default": None, "required": False, "type": "int"},
                            "retransmit_interval": {"default": None, "required": False, "type": "int"},
                            "type": {"default": None, "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "nssa": {"default": None, "required": False, "type": "bool"},
                    "range": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "address": {"default": None, "required": True, "type": "str"},
                            "cost": {"default": None, "required": False, "type": "int"},
                            "no_advertise": {"default": False, "required": False, "type": "bool"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "stub": {"default": None, "required": False, "type": "bool"},
                },
                "required": False,
                "type": "list",
            },
            "delay": {"default": None, "required": False, "type": "int"},
            "external": {"default": None, "required": False, "type": "int"},
            "initial_hold": {"default": None, "required": False, "type": "int"},
            "inter_area": {"default": None, "required": False, "type": "int"},
            "intra_area": {"default": None, "required": False, "type": "int"},
            "max_hold": {"default": None, "required": False, "type": "int"},
            "metric": {"default": None, "required": False, "type": "int"},
            "metric_type": {"default": None, "required": False, "type": "str"},
            "originate": {"default": None, "required": False, "type": "bool"},
            "redistribute": {
                "default": None,
                "elements": "dict",
                "options": {
                    "dia": {"default": True, "required": False, "type": "bool"},
                    "protocol": {"default": None, "required": True, "type": "str"},
                    "route_policy": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "reference_bandwidth": {"default": None, "required": False, "type": "int"},
            "rfc1583": {"default": True, "required": False, "type": "bool"},
            "route_policy": {
                "default": None,
                "elements": "dict",
                "options": {
                    "direction": {"default": None, "required": True, "type": "str"},
                    "pol_name": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "router_id": {"default": None, "required": False, "type": "str"},
            "router_lsa": {
                "default": None,
                "elements": "dict",
                "options": {
                    "ad_type": {"default": None, "required": True, "type": "str"},
                    "time": {"default": None, "required": True, "type": "int"},
                },
                "required": False,
                "type": "list",
            },
        },
        "required": False,
        "type": "dict",
    }
}
