cisco_vpn_interface_definition = {
    "cisco_vpn_interface": {
        "default": None,
        "options": {
            "access_list_ipv4": {
                "default": None,
                "elements": "dict",
                "options": {
                    "acl_name": {"default": None, "required": True, "type": "str"},
                    "direction": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "access_list_ipv6": {
                "default": None,
                "elements": "dict",
                "options": {
                    "acl_name": {"default": None, "required": True, "type": "str"},
                    "direction": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "all": {"default": None, "required": False, "type": "str"},
            "arp_timeout": {"default": None, "required": False, "type": "str"},
            "auto_bandwidth_detect": {"default": None, "required": False, "type": "str"},
            "autonegotiate": {"default": None, "required": False, "type": "str"},
            "bandwidth_down": {"default": None, "required": False, "type": "str"},
            "bandwidth_downstream": {"default": None, "required": False, "type": "str"},
            "bandwidth_up": {"default": None, "required": False, "type": "str"},
            "bandwidth_upstream": {"default": None, "required": False, "type": "str"},
            "bgp": {"default": None, "required": False, "type": "str"},
            "bind": {"default": None, "required": False, "type": "str"},
            "block_non_source_ip": {"default": None, "required": False, "type": "str"},
            "border": {"default": None, "required": False, "type": "str"},
            "carrier": {"default": None, "required": False, "type": "str"},
            "clear_dont_fragment": {"default": None, "required": False, "type": "str"},
            "control_connections": {"default": None, "required": False, "type": "str"},
            "core_region": {"default": None, "required": False, "type": "str"},
            "dhcp": {"default": None, "required": False, "type": "str"},
            "dhcp_distance": {"default": None, "required": False, "type": "str"},
            "dhcp_helper": {"default": None, "elements": "str", "required": False, "type": "list"},
            "dhcp_helper_v6": {
                "default": None,
                "elements": "dict",
                "options": {
                    "address": {"default": None, "required": True, "type": "str"},
                    "vpn": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "dhcp_ipv4_client": {"default": None, "required": False, "type": "str"},
            "dhcp_ipv6_client": {"default": None, "required": False, "type": "str"},
            "dmax": {"default": None, "required": False, "type": "str"},
            "dmin": {"default": None, "required": False, "type": "str"},
            "dns": {"default": None, "required": False, "type": "str"},
            "dst_ip": {"default": None, "required": False, "type": "str"},
            "duplex": {"default": None, "required": False, "type": "str"},
            "enable": {"default": None, "required": False, "type": "str"},
            "enable_core_region": {"default": None, "required": False, "type": "str"},
            "enable_sgt_authorization_and_forwarding": {"default": None, "required": False, "type": "str"},
            "enable_sgt_enforcement": {"default": None, "required": False, "type": "str"},
            "enable_sgt_propagation": {"default": None, "required": False, "type": "str"},
            "enforcement_sgt": {"default": None, "required": False, "type": "str"},
            "exclude_controller_group_list": {"default": None, "elements": "str", "required": False, "type": "list"},
            "group": {"default": None, "elements": "str", "required": False, "type": "list"},
            "hello_interval": {"default": None, "required": False, "type": "str"},
            "hello_tolerance": {"default": None, "required": False, "type": "str"},
            "https": {"default": None, "required": False, "type": "str"},
            "icmp": {"default": None, "required": False, "type": "str"},
            "icmp_redirect_disable": {"default": None, "required": False, "type": "str"},
            "if_name": {"default": None, "required": False, "type": "str"},
            "interface_description": {"default": None, "required": False, "type": "str"},
            "intrf_mtu": {"default": None, "required": False, "type": "str"},
            "ip": {
                "default": None,
                "elements": "dict",
                "options": {
                    "addr": {"default": None, "required": True, "type": "str"},
                    "mac": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "ip_directed_broadcast": {"default": None, "required": False, "type": "str"},
            "iperf_server": {"default": None, "required": False, "type": "str"},
            "ipv4_address": {"default": None, "required": False, "type": "str"},
            "ipv6_address": {"default": None, "required": False, "type": "str"},
            "ipv6_vrrp": {
                "default": None,
                "elements": "dict",
                "options": {
                    "grp_id": {"default": None, "required": True, "type": "str"},
                    "ipv6": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "ipv6_link_local": {"default": None, "required": True, "type": "str"},
                            "prefix": {"default": None, "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "priority": {"default": None, "required": False, "type": "str"},
                    "timer": {"default": None, "required": False, "type": "str"},
                    "track_omp": {"default": None, "required": False, "type": "bool"},
                    "track_prefix_list": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "last_resort_circuit": {"default": None, "required": False, "type": "str"},
            "load_interval": {"default": None, "required": False, "type": "str"},
            "loopback_interface": {"default": None, "required": False, "type": "str"},
            "low_bandwidth_link": {"default": None, "required": False, "type": "str"},
            "mac_address": {"default": None, "required": False, "type": "str"},
            "max_control_connections": {"default": None, "required": False, "type": "str"},
            "media_type": {"default": None, "required": False, "type": "str"},
            "mode": {"default": None, "required": False, "type": "str"},
            "mtu": {"default": None, "required": False, "type": "str"},
            "nat": {"default": None, "required": False, "type": "str"},
            "nat64": {"default": None, "required": False, "type": "str"},
            "nat66": {"default": None, "required": False, "type": "str"},
            "nat_choice": {"default": None, "required": False, "type": "str"},
            "nat_range_end": {"default": None, "required": False, "type": "str"},
            "nat_range_start": {"default": None, "required": False, "type": "str"},
            "nat_refresh_interval": {"default": None, "required": False, "type": "str"},
            "netconf": {"default": None, "required": False, "type": "str"},
            "network_broadcast": {"default": None, "required": False, "type": "str"},
            "ntp": {"default": None, "required": False, "type": "str"},
            "ospf": {"default": None, "required": False, "type": "str"},
            "overload": {"default": None, "required": False, "type": "str"},
            "per_tunnel_qos": {"default": None, "required": False, "type": "str"},
            "per_tunnel_qos_aggregator": {"default": None, "required": False, "type": "str"},
            "period": {"default": None, "required": False, "type": "str"},
            "poe": {"default": None, "required": False, "type": "str"},
            "port_hop": {"default": None, "required": False, "type": "str"},
            "prefix_length": {"default": None, "required": False, "type": "str"},
            "propagate_sgt": {"default": None, "required": False, "type": "str"},
            "qos_adaptive": {"default": None, "required": False, "type": "str"},
            "qos_map": {"default": None, "required": False, "type": "str"},
            "qos_map_vpn": {"default": None, "required": False, "type": "str"},
            "restrict": {"default": None, "required": False, "type": "str"},
            "rule_name": {"default": None, "required": False, "type": "str"},
            "secondary_ipv4_address": {
                "default": None,
                "elements": "dict",
                "options": {"address": {"default": None, "required": False, "type": "str"}},
                "required": False,
                "type": "list",
            },
            "secondary_ipv6_address": {
                "default": None,
                "elements": "dict",
                "options": {"address": {"default": None, "required": False, "type": "str"}},
                "required": False,
                "type": "list",
            },
            "secondary_region": {"default": None, "required": False, "type": "str"},
            "security_group_tag": {"default": None, "required": False, "type": "str"},
            "service_provider": {"default": None, "required": False, "type": "str"},
            "shaping_rate": {"default": None, "required": False, "type": "str"},
            "shutdown": {"default": None, "required": False, "type": "str"},
            "snmp": {"default": None, "required": False, "type": "str"},
            "speed": {"default": None, "required": False, "type": "str"},
            "src_ip": {"default": None, "required": False, "type": "str"},
            "sshd": {"default": None, "required": False, "type": "str"},
            "static": {
                "default": None,
                "elements": "dict",
                "options": {
                    "source_ip": {"default": None, "required": True, "type": "str"},
                    "source_vpn": {"default": None, "required": False, "type": "str"},
                    "static_nat_direction": {"default": "inside", "required": False, "type": "str"},
                    "translate_ip": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "static_nat66": {
                "default": None,
                "elements": "dict",
                "options": {
                    "source_prefix": {"default": None, "required": True, "type": "str"},
                    "source_vpn_id": {"default": None, "required": False, "type": "str"},
                    "translated_source_prefix": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "static_port_forward": {
                "default": None,
                "elements": "dict",
                "options": {
                    "proto": {"default": None, "required": True, "type": "str"},
                    "source_ip": {"default": None, "required": True, "type": "str"},
                    "source_port": {"default": None, "required": False, "type": "str"},
                    "source_vpn": {"default": None, "required": False, "type": "str"},
                    "static_nat_direction": {"default": "inside", "required": False, "type": "str"},
                    "translate_ip": {"default": None, "required": True, "type": "str"},
                    "translate_port": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "stun": {"default": None, "required": False, "type": "str"},
            "tcp_mss_adjust": {"default": None, "required": False, "type": "str"},
            "tcp_timeout": {"default": None, "required": False, "type": "str"},
            "tloc_encapsulation": {
                "default": None,
                "elements": "dict",
                "options": {
                    "encap": {"default": None, "required": True, "type": "str"},
                    "preference": {"default": None, "required": False, "type": "str"},
                    "weight": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "tloc_extension": {"default": None, "required": False, "type": "str"},
            "tracker": {"default": None, "elements": "str", "required": False, "type": "list"},
            "trusted": {"default": None, "required": False, "type": "str"},
            "tunnel_tcp_mss_adjust": {"default": None, "required": False, "type": "str"},
            "tunnels_bandwidth": {"default": None, "required": False, "type": "str"},
            "udp_timeout": {"default": None, "required": False, "type": "str"},
            "umax": {"default": None, "required": False, "type": "str"},
            "umin": {"default": None, "required": False, "type": "str"},
            "value": {"default": None, "required": False, "type": "str"},
            "vbond_as_stun_server": {"default": None, "required": False, "type": "str"},
            "vmanage_connection_preference": {"default": None, "required": False, "type": "str"},
            "vrrp": {
                "default": None,
                "elements": "dict",
                "options": {
                    "address": {"default": None, "required": False, "type": "str"},
                    "grp_id": {"default": None, "required": True, "type": "str"},
                    "ipv4_secondary": {
                        "default": None,
                        "elements": "dict",
                        "options": {"address": {"default": None, "required": True, "type": "str"}},
                        "required": False,
                        "type": "list",
                    },
                    "priority": {"default": None, "required": False, "type": "str"},
                    "timer": {"default": None, "required": False, "type": "str"},
                    "tloc_change_pref": {"default": None, "required": False, "type": "bool"},
                    "track_omp": {"default": None, "required": False, "type": "bool"},
                    "track_prefix_list": {"default": None, "required": False, "type": "str"},
                    "tracking_object": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "decrement": {"default": None, "required": True, "type": "str"},
                            "name": {"default": None, "required": True, "type": "str"},
                            "track_action": {"default": "Decrement", "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "value": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "xconnect": {"default": None, "required": False, "type": "str"},
        },
        "required": False,
        "type": "dict",
    }
}
