cisco_vpn_definition = {
    "cisco_vpn": {
        "default": None,
        "options": {
            "advertise": {
                "default": None,
                "elements": "dict",
                "options": {
                    "prefix_list": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "aggregate_only": {"default": None, "required": False, "type": "bool"},
                            "prefix_entry": {"default": None, "required": True, "type": "str"},
                            "region": {"default": None, "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "protocol": {"default": None, "required": True, "type": "str"},
                    "protocol_sub_type": {"default": None, "elements": "str", "required": False, "type": "list"},
                    "route_policy": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "dns": {
                "default": None,
                "elements": "dict",
                "options": {
                    "dns_addr": {"default": None, "required": False, "type": "str"},
                    "role": {"default": "primary", "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "dns_ipv6": {
                "default": None,
                "elements": "dict",
                "options": {
                    "dns_addr": {"default": None, "required": False, "type": "str"},
                    "role": {"default": "primary", "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "gre_route": {
                "default": None,
                "elements": "dict",
                "options": {
                    "interface": {"default": None, "elements": "str", "required": False, "type": "list"},
                    "prefix": {"default": None, "required": True, "type": "str"},
                    "vpn": {"default": None, "required": True, "type": "int"},
                },
                "required": False,
                "type": "list",
            },
            "host": {
                "default": None,
                "elements": "dict",
                "options": {
                    "hostname": {"default": None, "required": True, "type": "str"},
                    "ip": {"default": None, "elements": "str", "required": True, "type": "list"},
                },
                "required": False,
                "type": "list",
            },
            "ipsec_route": {
                "default": None,
                "elements": "dict",
                "options": {
                    "interface": {"default": None, "elements": "str", "required": False, "type": "list"},
                    "prefix": {"default": None, "required": True, "type": "str"},
                    "vpn": {"default": None, "required": True, "type": "int"},
                },
                "required": False,
                "type": "list",
            },
            "ipv6_advertise": {
                "default": None,
                "elements": "dict",
                "options": {
                    "prefix_list": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "aggregate_only": {"default": None, "required": False, "type": "bool"},
                            "prefix_entry": {"default": None, "required": True, "type": "str"},
                            "region": {"default": None, "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "protocol": {"default": None, "required": True, "type": "str"},
                    "protocol_sub_type": {"default": None, "elements": "str", "required": False, "type": "list"},
                    "route_policy": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "layer4": {"default": None, "required": False, "type": "bool"},
            "natpool": {
                "default": None,
                "elements": "dict",
                "options": {
                    "direction": {"default": None, "required": True, "type": "str"},
                    "name": {"default": None, "required": True, "type": "int"},
                    "overload": {"default": "true", "required": False, "type": "str"},
                    "prefix_length": {"default": None, "required": False, "type": "int"},
                    "range_end": {"default": None, "required": False, "type": "str"},
                    "range_start": {"default": None, "required": False, "type": "str"},
                    "tracker_id": {"default": None, "required": False, "type": "int"},
                },
                "required": False,
                "type": "list",
            },
            "omp_admin_distance_ipv4": {"default": None, "required": False, "type": "int"},
            "omp_admin_distance_ipv6": {"default": None, "required": False, "type": "int"},
            "org_name": {"default": None, "required": False, "type": "str"},
            "pool": {
                "default": None,
                "elements": "dict",
                "options": {
                    "end_address": {"default": None, "required": True, "type": "str"},
                    "leak_from_global": {"default": None, "required": True, "type": "bool"},
                    "leak_from_global_protocol": {"default": None, "required": True, "type": "str"},
                    "leak_to_global": {"default": None, "required": True, "type": "bool"},
                    "name": {"default": None, "required": True, "type": "str"},
                    "overload": {"default": None, "required": False, "type": "bool"},
                    "start_address": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "port_forward": {
                "default": None,
                "elements": "dict",
                "options": {
                    "pool_name": {"default": None, "required": False, "type": "int"},
                    "proto": {"default": None, "required": True, "type": "str"},
                    "source_ip": {"default": None, "required": True, "type": "str"},
                    "source_port": {"default": None, "required": True, "type": "int"},
                    "translate_ip": {"default": None, "required": True, "type": "str"},
                    "translate_port": {"default": None, "required": True, "type": "int"},
                },
                "required": False,
                "type": "list",
            },
            "route_export": {
                "default": None,
                "elements": "dict",
                "options": {
                    "protocol": {"default": None, "required": True, "type": "str"},
                    "protocol_sub_type": {"default": None, "elements": "str", "required": True, "type": "list"},
                    "redistribute": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "protocol": {"default": None, "required": True, "type": "str"},
                            "route_policy": {"default": None, "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "route_policy": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "route_import": {
                "default": None,
                "elements": "dict",
                "options": {
                    "protocol": {"default": None, "required": True, "type": "str"},
                    "protocol_sub_type": {"default": None, "elements": "str", "required": True, "type": "list"},
                    "redistribute": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "protocol": {"default": None, "required": True, "type": "str"},
                            "route_policy": {"default": None, "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "route_policy": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "route_import_from": {
                "default": None,
                "elements": "dict",
                "options": {
                    "protocol": {"default": None, "required": True, "type": "str"},
                    "protocol_sub_type": {"default": None, "elements": "str", "required": True, "type": "list"},
                    "redistribute": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "protocol": {"default": None, "required": True, "type": "str"},
                            "route_policy": {"default": None, "required": False, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "route_policy": {"default": None, "required": False, "type": "str"},
                    "source_vpn": {"default": None, "required": True, "type": "int"},
                },
                "required": False,
                "type": "list",
            },
            "route_v4": {
                "default": None,
                "elements": "dict",
                "options": {
                    "dhcp": {"default": None, "required": False, "type": "bool"},
                    "distance": {"default": None, "required": False, "type": "int"},
                    "next_hop": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "address": {"default": None, "required": False, "type": "str"},
                            "distance": {"default": None, "required": False, "type": "int"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "next_hop_with_track": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "address": {"default": None, "required": False, "type": "str"},
                            "distance": {"default": None, "required": False, "type": "int"},
                            "tracker": {"default": None, "required": True, "type": "str"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "null0": {"default": None, "required": False, "type": "bool"},
                    "prefix": {"default": None, "required": False, "type": "str"},
                    "route_interface": {
                        "default": None,
                        "options": {
                            "interface_name": {"default": None, "required": True, "type": "str"},
                            "interface_next_hop": {
                                "default": None,
                                "elements": "dict",
                                "options": {
                                    "address": {"default": None, "required": False, "type": "str"},
                                    "distance": {"default": None, "required": False, "type": "int"},
                                },
                                "required": False,
                                "type": "list",
                            },
                        },
                        "required": False,
                        "type": "dict",
                    },
                    "vpn": {"default": None, "required": False, "type": "int"},
                },
                "required": False,
                "type": "list",
            },
            "route_v6": {
                "default": None,
                "elements": "dict",
                "options": {
                    "nat": {"default": None, "required": False, "type": "str"},
                    "next_hop": {
                        "default": None,
                        "elements": "dict",
                        "options": {
                            "address": {"default": None, "required": True, "type": "str"},
                            "distance": {"default": None, "required": False, "type": "int"},
                        },
                        "required": False,
                        "type": "list",
                    },
                    "null0": {"default": None, "required": False, "type": "bool"},
                    "prefix": {"default": None, "required": True, "type": "str"},
                    "vpn": {"default": None, "required": False, "type": "int"},
                },
                "required": False,
                "type": "list",
            },
            "service": {
                "default": None,
                "elements": "dict",
                "options": {
                    "address": {"default": None, "elements": "str", "required": False, "type": "list"},
                    "interface": {"default": None, "required": False, "type": "str"},
                    "svc_type": {"default": None, "required": True, "type": "str"},
                    "track_enable": {"default": None, "required": False, "type": "bool"},
                },
                "required": False,
                "type": "list",
            },
            "service_route": {
                "default": None,
                "elements": "dict",
                "options": {
                    "prefix": {"default": None, "required": True, "type": "str"},
                    "service": {"default": "sig", "required": False, "type": "str"},
                    "vpn": {"default": None, "required": True, "type": "int"},
                },
                "required": False,
                "type": "list",
            },
            "static": {
                "default": None,
                "elements": "dict",
                "options": {
                    "pool_name": {"default": None, "required": False, "type": "int"},
                    "source_ip": {"default": None, "required": False, "type": "str"},
                    "static_nat_direction": {"default": None, "required": True, "type": "str"},
                    "tracker_id": {"default": None, "required": False, "type": "int"},
                    "translate_ip": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "subnet_static": {
                "default": None,
                "elements": "dict",
                "options": {
                    "prefix_length": {"default": None, "required": True, "type": "int"},
                    "source_ip_subnet": {"default": None, "required": True, "type": "str"},
                    "static_nat_direction": {"default": None, "required": True, "type": "str"},
                    "tracker_id": {"default": None, "required": False, "type": "int"},
                    "translate_ip_subnet": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "tenant_vpn_id": {"default": None, "required": False, "type": "int"},
            "vpn_id": {"default": None, "required": False, "type": "int"},
            "vpn_name": {"default": None, "required": False, "type": "str"},
        },
        "required": False,
        "type": "dict",
    }
}
