system_vsmart_definition = {
    "system_vsmart": {
        "default": None,
        "options": {
            "admin_tech_on_failure": {"default": True, "required": False, "type": "bool"},
            "compatible": {
                "default": None,
                "elements": "dict",
                "options": {
                    "color_1": {"default": None, "required": False, "type": "str"},
                    "color_2": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "control_session_pps": {"default": None, "required": False, "type": "int"},
            "controller_group_id": {"default": None, "required": False, "type": "int"},
            "description": {"default": None, "required": False, "type": "str"},
            "device_groups": {"default": None, "elements": "str", "required": False, "type": "list"},
            "dns_cache_timeout": {"default": None, "required": False, "type": "int"},
            "dual_stack_ipv6": {
                "default": None,
                "options": {"name": {"default": "system_ipv6-strict-control", "required": True, "type": "str"}},
                "required": False,
                "type": "raw",
            },
            "host_name": {
                "default": None,
                "options": {"name": {"default": "system_host_name", "required": True, "type": "str"}},
                "required": False,
                "type": "raw",
            },
            "idle_timeout": {"default": None, "required": False, "type": "int"},
            "incompatible": {
                "default": None,
                "elements": "dict",
                "options": {
                    "color_1": {"default": None, "required": False, "type": "str"},
                    "color_2": {"default": None, "required": False, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "iptables_enable": {"default": True, "required": False, "type": "bool"},
            "latitude": {"default": None, "required": False, "type": "int"},
            "location": {"default": None, "required": False, "type": "str"},
            "longitude": {"default": None, "required": False, "type": "int"},
            "management_region": {"default": None, "required": False, "type": "bool"},
            "overlay_id": {"default": None, "required": False, "type": "int"},
            "port_hop": {"default": None, "required": False, "type": "bool"},
            "port_offset": {"default": None, "required": False, "type": "int"},
            "region_list_id": {"default": None, "required": False, "type": "int"},
            "site_id": {
                "default": None,
                "options": {"name": {"default": "system_site_id", "required": True, "type": "str"}},
                "required": False,
                "type": "raw",
            },
            "system_ip": {
                "default": None,
                "options": {"name": {"default": "system_system_ip", "required": True, "type": "str"}},
                "required": False,
                "type": "raw",
            },
            "system_tunnel_mtu": {"default": None, "required": False, "type": "int"},
            "timezone": {"default": "UTC", "required": False, "type": "str"},
            "topology": {"default": None, "elements": "str", "required": False, "type": "list"},
            "track_default_gateway": {"default": True, "required": False, "type": "bool"},
            "track_transport": {"default": True, "required": False, "type": "bool"},
        },
        "required": False,
        "type": "dict",
    }
}
