system_vsmart_definition = { 'system_vsmart': { 'default': None,
                     'options': { 'admin_tech_on_failure': { 'default': None,
                                                             'required': False,
                                                             'type': 'bool'},
                                  'compatible': { 'default': None,
                                                  'options': { 'color_1': { 'default': None,
                                                                            'required': False,
                                                                            'type': 'str'},
                                                               'color_2': { 'default': None,
                                                                            'required': False,
                                                                            'type': 'str'}},
                                                  'required': False,
                                                  'type': 'dict'},
                                  'control_session_pps': { 'default': None,
                                                           'required': False,
                                                           'type': 'int'},
                                  'controller_group_id': { 'default': None,
                                                           'required': False,
                                                           'type': 'int'},
                                  'description': { 'default': None,
                                                   'required': False,
                                                   'type': 'str'},
                                  'device_groups': { 'default': None,
                                                     'required': False,
                                                     'type': 'str'},
                                  'dns_cache_timeout': { 'default': None,
                                                         'required': False,
                                                         'type': 'int'},
                                  'dual_stack_ipv6': { 'default': None,
                                                       'required': False,
                                                       'type': 'bool'},
                                  'host_name': { 'default': None,
                                                 'required': False,
                                                 'type': 'str'},
                                  'idle_timeout': { 'default': None,
                                                    'required': False,
                                                    'type': 'int'},
                                  'incompatible': { 'default': None,
                                                    'options': { 'color_1': { 'default': None,
                                                                              'required': False,
                                                                              'type': 'str'},
                                                                 'color_2': { 'default': None,
                                                                              'required': False,
                                                                              'type': 'str'}},
                                                    'required': False,
                                                    'type': 'dict'},
                                  'iptables_enable': { 'default': None,
                                                       'required': False,
                                                       'type': 'bool'},
                                  'latitude': { 'default': None,
                                                'required': False,
                                                'type': 'int'},
                                  'location': { 'default': None,
                                                'required': False,
                                                'type': 'str'},
                                  'longitude': { 'default': None,
                                                 'required': False,
                                                 'type': 'int'},
                                  'management_region': { 'default': None,
                                                         'required': False,
                                                         'type': 'bool'},
                                  'overlay_id': { 'default': None,
                                                  'required': False,
                                                  'type': 'int'},
                                  'port_hop': { 'default': None,
                                                'required': False,
                                                'type': 'bool'},
                                  'port_offset': { 'default': None,
                                                   'required': False,
                                                   'type': 'int'},
                                  'region_list_id': { 'default': None,
                                                      'required': False,
                                                      'type': 'int'},
                                  'site_id': { 'default': None,
                                               'required': False,
                                               'type': 'int'},
                                  'system_ip': { 'default': None,
                                                 'required': False,
                                                 'type': 'str'},
                                  'system_tunnel_mtu': { 'default': None,
                                                         'required': False,
                                                         'type': 'str'},
                                  'timezone': { 'default': None,
                                                'required': False,
                                                'type': 'str'},
                                  'topology': { 'default': None,
                                                'required': False,
                                                'type': 'str'},
                                  'track_default_gateway': { 'default': None,
                                                             'required': False,
                                                             'type': 'bool'},
                                  'track_transport': { 'default': None,
                                                       'required': False,
                                                       'type': 'bool'}},
                     'required': False,
                     'type': 'dict'}}
