vpn_vsmart_interface_definition = {
    "vpn_vsmart_interface": {
        "default": None,
        "options": {
            "all": {"default": None, "required": False, "type": "bool"},
            "autonegotiate": {"default": True, "required": False, "type": "bool"},
            "carrier": {"default": None, "required": False, "type": "str"},
            "clear_dont_fragment": {"default": False, "required": False, "type": "bool"},
            "dhcp": {"default": None, "required": False, "type": "bool"},
            "dhcp_distance": {"default": None, "required": False, "type": "int"},
            "dhcp_ipv4_client": {"default": None, "required": False, "type": "bool"},
            "dhcp_ipv6_client": {"default": None, "required": False, "type": "bool"},
            "dhcp_ipv6_distance": {"default": None, "required": False, "type": "int"},
            "dhcp_rapid_commit": {"default": None, "required": False, "type": "bool"},
            "dns": {"default": None, "required": False, "type": "bool"},
            "duplex": {"default": None, "required": False, "type": "str"},
            "flow_control": {"default": None, "required": False, "type": "str"},
            "group": {"default": None, "elements": "int", "required": False, "type": "list"},
            "hello_interval": {"default": None, "required": False, "type": "int"},
            "hello_tolerance": {"default": None, "required": False, "type": "int"},
            "icmp": {"default": None, "required": False, "type": "bool"},
            "if_name": {"default": None, "required": False, "type": "str"},
            "interface_description": {"default": None, "required": False, "type": "str"},
            "ip": {
                "default": None,
                "elements": "dict",
                "options": {
                    "addr": {"default": None, "required": True, "type": "str"},
                    "mac": {"default": None, "required": True, "type": "str"},
                },
                "required": False,
                "type": "list",
            },
            "ipv4_address": {"default": None, "required": False, "type": "str"},
            "ipv6_address": {"default": None, "required": False, "type": "str"},
            "mac_address": {"default": None, "required": False, "type": "str"},
            "mtu": {"default": None, "required": False, "type": "int"},
            "nat_refresh_interval": {"default": None, "required": False, "type": "int"},
            "netconf": {"default": None, "required": False, "type": "bool"},
            "ntp": {"default": None, "required": False, "type": "bool"},
            "pmtu": {"default": False, "required": False, "type": "bool"},
            "shutdown": {"default": False, "required": False, "type": "bool"},
            "speed": {"default": None, "required": False, "type": "str"},
            "sshd": {"default": None, "required": False, "type": "bool"},
            "stun": {"default": None, "required": False, "type": "bool"},
            "tcp_mss_adjust": {"default": None, "required": False, "type": "int"},
            "value": {"default": None, "required": False, "type": "str"},
        },
        "required": False,
        "type": "dict",
    }
}
